common_volumes:
  - "{{ homeassistantfrigate_homeassistant_required_volumes.localtime }}:/etc/localtime:ro"
  - "{{ homeassistantfrigate_homeassistant_required_volumes.timezone }}:/etc/timezone:ro"

default_logging:
  driver: "json-file"
  options:
    max-size: "{{ homeassistantfrigate_docker_log_max_size }}"
    max-file: "{{ homeassistantfrigate_docker_log_max_file }}"

external_network:
  default:
    external: true
    name: homeassistant-frigate_default
