---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart Avahi service
  ansible.builtin.systemd_service:
    name: avahi-daemon
    daemon_reload: true
    state: started
    enabled: true
  become: true

- name: Restart homeassistant
  community.docker.docker_container:
    name: homeassistant
    restart: true

- name: Load docker-ble-policy
  ansible.builtin.command: apparmor_parser -r -W /etc/apparmor.d/docker-ble-policy
  become: true
  changed_when: true

- name: Update /etc/hosts
  # https://github.com/andornaut/docker_etc_hosts
  ansible.builtin.command: /usr/local/bin/docker_etc_hosts
  become: true
  changed_when: true
