---
- name: Update dynamic linker cache
  ansible.builtin.command: ldconfig
  become: true

- name: Install system dependencies
  block:
    - name: Install system packages
      ansible.builtin.apt:
        name:
          - clang
          - gcc-14
          - g++-14
          #- libdbus-1-dev  # A newer version is installed in hypr.yml
          - libdisplay-info-dev
          - libegl1-mesa-dev
          - libgbm-dev
          - libinput-dev
          - libpango1.0-dev
          - libpipewire-0.3-dev
          - libseat-dev
          - libsystemd-dev
          - libudev-dev
          - libwayland-dev
          - libxcb-cursor-dev
          - libxkbcommon-dev
          - wayland-scanner++
          - wl-clipboard
          - xdg-desktop-portal
          - xdg-desktop-portal-gnome
          - xdg-desktop-portal-gtk
          - xwayland
          - xwayland-run

          # wayland dependencies
          - doxygen
          - graphviz
          - xmlto
          - xsltproc

          # hypr dependencies
          - g++-14
          - gcc-14
          - libmagic-dev
          - libpugixml-dev
          # Must not be installed, b/c it conflicts with v2.1.0 which is installed from source
          #- libsdbus-c++-dev
          - libspng-dev
        state: latest
        install_recommends: false
        update_cache: true
      become: true

    - name: Configure GCC alternatives
      community.general.alternatives:
        name: "{{ item }}"
        path: "/usr/bin/{{ item }}-14"
        link: "/usr/bin/{{ item }}"
        state: selected
      loop:
        - gcc
        - g++
      become: true
  tags: [packages]

- name: Install libsdbus
  block:
    - name: Create a temporary directory for libsdbus
      ansible.builtin.tempfile:
        state: directory
      register: libsdbus_tmp

    - name: Get the latest version of libsdbus
      ansible.builtin.uri:
        url: https://api.github.com/repos/Kistler-Group/sdbus-cpp/releases/latest
        return_content: true
      register: libsdbus_version

    - name: Download and unarchive libsdbus {{ libsdbus_version.json.name }}
      ansible.builtin.unarchive:
        src: https://github.com/Kistler-Group/sdbus-cpp/archive/refs/tags/{{ libsdbus_version.json.name }}.tar.gz
        dest: "{{ libsdbus_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Create build directory for libsdbus
      ansible.builtin.file:
        path: "{{ libsdbus_tmp.path }}/build"
        state: directory
        mode: "0755"

    # Workaround: Install into /usr instead of the default of /usr/local
    # https://github.com/hyprwm/hypridle/issues/109#issuecomment-2678603712
    - name: Build libsdbus (1/2)
      ansible.builtin.shell:
        cmd: cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local
        chdir: "{{ libsdbus_tmp.path }}/build"

    - name: Build libsdbus (2/2)
      ansible.builtin.shell:
        cmd: cmake --build .
        chdir: "{{ libsdbus_tmp.path }}/build"

    - name: Install libsdbus
      ansible.builtin.command:
        cmd: cmake --build . --target install
        chdir: "{{ libsdbus_tmp.path }}/build"
      become: true
  tags: [libsdbus]

- name: Install Wayland (for wayland-scanner)
  block:
    - name: Get latest release info from GitLab API
      ansible.builtin.uri:
        url: "https://gitlab.freedesktop.org/api/v4/projects/121/releases"
        method: GET
        return_content: true
      register: wayland_scanner_info

    - name: Set Wayland variables
      ansible.builtin.set_fact:
        wayland_scanner_version: "{{ wayland_scanner_info.json[0].tag_name }}"
        wayland_scanner_download_url: "{{ wayland_scanner_info.json[0].assets.sources | selectattr('format', 'equalto', 'tar.gz') | map(attribute='url') | first }}"

    - name: Create a temporary directory for Wayland
      ansible.builtin.tempfile:
        state: directory
      register: wayland_scanner_tmp

    - name: Download and unarchive Wayland {{ wayland_scanner_version }}
      ansible.builtin.unarchive:
        src: "{{ wayland_scanner_download_url }}"
        dest: "{{ wayland_scanner_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Create build directory for Wayland
      ansible.builtin.file:
        path: "{{ wayland_scanner_tmp.path }}/build"
        state: directory
        mode: "0755"

    - name: Configure Wayland
      ansible.builtin.command:
        cmd: meson build/ --prefix=/usr/local --buildtype=release
        chdir: "{{ wayland_scanner_tmp.path }}"

    - name: Build Wayland
      ansible.builtin.command:
        cmd: ninja
        chdir: "{{ wayland_scanner_tmp.path }}/build"

    - name: Install Wayland
      ansible.builtin.command:
        cmd: ninja install
        chdir: "{{ wayland_scanner_tmp.path }}/build"
      become: true
  tags: [wayland]

- name: Install wayland-protocols
  block:
    - name: Get latest release info from GitLab API
      ansible.builtin.uri:
        url: "https://gitlab.freedesktop.org/api/v4/projects/2891/releases"
        method: GET
        return_content: true
      register: wayland_protocols_info

    - name: Set wayland-protocols variables
      ansible.builtin.set_fact:
        wayland_protocols_version: "{{ wayland_protocols_info.json[0].tag_name }}"
        wayland_protocols_download_url: "{{ wayland_protocols_info.json[0].assets.sources | selectattr('format', 'equalto', 'tar.gz') | map(attribute='url') | first }}"

    - name: Create a temporary directory for wayland-protocols
      ansible.builtin.tempfile:
        state: directory
      register: wayland_protocols_tmp

    - name: Download and unarchive wayland-protocols {{ wayland_protocols_version }}
      ansible.builtin.unarchive:
        src: "{{ wayland_protocols_download_url }}"
        dest: "{{ wayland_protocols_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Create build directory for wayland-protocols
      ansible.builtin.file:
        path: "{{ wayland_protocols_tmp.path }}/build"
        state: directory
        mode: "0755"

    - name: Configure wayland-protocols
      ansible.builtin.command:
        cmd: meson build/ --prefix=/usr/local --buildtype=release
        chdir: "{{ wayland_protocols_tmp.path }}"

    - name: Build wayland-protocols
      ansible.builtin.command:
        cmd: ninja
        chdir: "{{ wayland_protocols_tmp.path }}/build"

    - name: Install wayland-protocols
      ansible.builtin.command:
        cmd: ninja install
        chdir: "{{ wayland_protocols_tmp.path }}/build"
      become: true
  tags: [wayland]

- name: Install hyprland-protocols
  block:
    - name: Get latest release info from GitHub API
      ansible.builtin.uri:
        url: "https://api.github.com/repos/hyprwm/hyprland-protocols/releases/latest"
        method: GET
        return_content: true
      register: hyprland_protocols_info

    - name: Set hyprland-protocols variables
      ansible.builtin.set_fact:
        hyprland_protocols_version: "{{ hyprland_protocols_info.json.tag_name }}"
        hyprland_protocols_download_url: "{{ hyprland_protocols_info.json.tarball_url }}"

    - name: Create a temporary directory for hyprland-protocols
      ansible.builtin.tempfile:
        state: directory
      register: hyprland_protocols_tmp

    - name: Download and unarchive hyprland-protocols {{ hyprland_protocols_version }}
      ansible.builtin.unarchive:
        src: "{{ hyprland_protocols_download_url }}"
        dest: "{{ hyprland_protocols_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Configure hyprland-protocols
      ansible.builtin.command:
        cmd: meson build/ --prefix=/usr/local --buildtype=release
        chdir: "{{ hyprland_protocols_tmp.path }}"

    - name: Build hyprland-protocols
      ansible.builtin.command:
        cmd: ninja
        chdir: "{{ hyprland_protocols_tmp.path }}/build"

    - name: Install hyprland-protocols
      ansible.builtin.command:
        cmd: ninja install
        chdir: "{{ hyprland_protocols_tmp.path }}/build"
      become: true
  tags: [hypr]
