---
- name: Create a temporary directory for xwayland-satellite
  tempfile:
    state: directory
  register: xwayland_tmp

- name: Get the latest version of xwayland-satellite
  uri:
    url: https://api.github.com/repos/Supreeeme/xwayland-satellite/releases/latest
    return_content: yes
  register: xwayland_version

- name: Download and unarchive xwayland-satellite
  ansible.builtin.unarchive:
    src: https://github.com/Supreeeme/xwayland-satellite/archive/refs/tags/{{ xwayland_version.json.name }}.tar.gz
    dest: "{{ xwayland_tmp.path }}"
    remote_src: true
    extra_opts:
      - --strip-components
      - 1

- name: Build xwayland-satellite
  command:
    cmd: cargo build --release -F systemd
    chdir: "{{ xwayland_tmp.path }}"

- name: Edit xwayland-satellite.service
  ansible.builtin.lineinfile:
    path: "{{ xwayland_tmp.path }}/resources/xwayland-satellite.service"
    regexp: "^ExecStart"
    line: ExecStart=/usr/local/bin/xwayland-satellite

- name: Install xwayland-satellite files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{ xwayland_tmp.path }}/resources/xwayland-satellite.service"
      dest: /etc/systemd/user/
    - src: "{{ xwayland_tmp.path }}/target/release/xwayland-satellite"
      dest: /usr/local/bin/
  become: true

- name: Enable and run xwayland-satellite.service
  systemd_service:
    name: xwayland-satellite.service
    daemon_reload: true
    enabled: true
    scope: user
    state: started
  become: true
  become_user: "{{ niri_systemd_username }}"
  when: niri_systemd_username is truthy
