---
galaxy_info:
  author: andornaut
  description: Configure Network Attached Storage (NAS) with LUKS encryption on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - nas
    - storage
    - luks
    - encryption
    - ubuntu
