---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

# Disable then enable, to update the WantedBy symlink when [Install] changes.
- name: Disable nas-mount.service
  ansible.builtin.systemd_service:
    name: nas-mount.service
    enabled: false
  become: true

- name: Enable nas-mount.service
  ansible.builtin.systemd_service:
    name: nas-mount.service
    enabled: true
  become: true
