---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

# Disable+enable updates the WantedBy symlink when the [Install] section changes
- name: Disable nas-mount.service
  ansible.builtin.systemd_service:
    name: nas-mount.service
    enabled: false
  become: true

- name: Enable nas-mount.service
  ansible.builtin.systemd_service:
    name: nas-mount.service
    enabled: true
  become: true
