---
galaxy_info:
  author: andornaut
  description: Install and configure desktop applications and utilities on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - desktop
    - applications
    - utilities
    - ubuntu
