# https://docs.frigate.video/configuration/index/
birdseye:
  mode: continuous
cameras:
  front:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@camera-front.example.com:554/cam/realmonitor?channel=1&subtype=0
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - record
            - rtmp
    motion:
      mask:
        - 618,28,1025,26,1280,85,1280,0,0,0,0,157,311,67
      # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
      # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
      # The value should be between 1 and 255.
      threshold: 40
    #   objects:
    #     track:
    #       # Added "car"
    #       - car
    #       - cat
    #       - dog
    #       - person
    record:
      events:
        required_zones:
          - frontyard
    snapshots:
      required_zones:
        - frontyard
    zones:
      frontyard:
        coordinates: 1280,720,1280,254,1072,184,280,158,145,206,251,366,41,597,213,720
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@camera-garage.example.com:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
            - rtmp
    motion:
      mask:
        - 323,64,185,80,188,0,328,0
    record:
      events:
        required_zones:
          - backyard
    snapshots:
      required_zones:
        - backyard
    zones:
      backyard:
        coordinates: 102,720,1037,720,1280,545,1280,219,710,139,360,166,346,78,191,99,69,267
  kid:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@camera-kid.example.com:443/videoMain
          roles:
            - detect
            - rtmp
    objects:
      track: []
    detect:
      enabled: False
    record:
      enabled: False
    snapshots:
      enabled: False
detectors:
  coral:
    # https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    type: edgetpu
    device: usb
  # Enabling the CPU detector prevents Frigate from restarting when the edgetpu detector isn't found,
  # which worksaround this issue:
  # https://github.com/blakeblackshear/frigate/issues/3259#issuecomment-1249408707
  # This issue doesn't occur - and so this workaround isn't necessary - when running the container in
  # `--privileged` mode
  #cpu1:
  #  type: cpu
  #  num_threads: 3
ffmpeg:
  hwaccel_args: preset-vaapi
  #  - -hwaccel
  #  - vaapi
  #  - -hwaccel_device
  #  - /dev/dri/renderD128
  #  - -hwaccel_output_format
  #  - yuv420p
mqtt:
  host: tron.example.com
objects:
  filters:
    person:
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive
      threshold: 0.75
  # Optional: list of objects to track from labelmap.txt
  track:
    - cat
    - dog
    - person # Default: person only
record:
  enabled: True
  events:
    # Save all recordings segments for events with any detected motion
    retain:
      default: 60
snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 365
  timestamp: True
timestamp_style:
  # "tl" (top left), "tr" (top right), "bl" (bottom left), "br" (bottom right)
  position: "tr"
  format: "%Y-%m-%d %H:%M:%S"
