---
- name: Initiate Letsencrypt DNS or HTTP challenge
  community.crypto.acme_certificate:
    account_email: "{{ letsencrypt_nginx_account_email }}"
    account_key_src: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/key/public.pem
    acme_directory: "{{ letsencrypt_nginx_acme_directory_url }}"
    acme_version: "{{ letsencrypt_nginx_acme_version }}"
    challenge: >-
      {% if item.cloudflare_api_token | default(false) %}dns-01{% else %}http-01{% endif %}
    csr: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/csr/{{
      item.csr_common_name | default(item.domain) | replace('*', '_') }}.csr
    # Set to `force: true` when switching between staging and production
    # force: true
    fullchain_dest: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/crt/{{
      item.csr_common_name | default(item.domain) | replace('*', '_') }}.crt
    remaining_days: "{{ letsencrypt_nginx_remaining_days }}"
    terms_agreed: true
  loop: "{{ letsencrypt_nginx_websites }}"
  register: letsencrypt_nginx_challenge
  when:
    - not item.use_selfsigned_certificate | default(false)
  become: true

# - ansible.builtin.debug:
#     var: letsencrypt_nginx_challenge

- name: Create DNS challenge TXT record
  community.general.cloudflare_dns:
    api_token: "{{ item.item.cloudflare_api_token }}"
    record: >-
      {{ item.challenge_data[item.item.csr_common_name
      | default(item.item.domain)]['dns-01'].record }}
    solo: true
    ttl: 60
    type: TXT
    value: >-
      {{ item.challenge_data[item.item.csr_common_name
      | default(item.item.domain)]['dns-01'].resource_value }}
    zone: "{{ item.item.cloudflare_api_zone }}"
  loop: "{{ letsencrypt_nginx_challenge.results }}"
  register: letsencrypt_nginx_dns_record
  when:
    - item is not skipped
    - item.changed
    - item.challenge_data
    - item.item.cloudflare_api_token is defined
    - not item.item.use_selfsigned_certificate | default(false)
  become: true

- name: Debug DNS record result
  ansible.builtin.debug:
    var: letsencrypt_nginx_dns_record

- name: Pause to allow DNS to update
  ansible.builtin.pause:
    # Pause for slightly longer than the DNS TTL to ensure that it has propagated to (potential) intermediaries.
    seconds: 300
#  when:
#    - dns_record.changed

- name: Create HTTP challenge resource directories
  ansible.builtin.file:
    path: >-
      {{ letsencrypt_nginx_docker_required_volumes.www }}/{{ item.item.domain }}/{{
      item.challenge_data[item.item.csr_common_name
      | default(item.item.domain)]['http-01']['resource'] | dirname }}
    state: directory
    mode: "0755"
  loop: "{{ letsencrypt_nginx_challenge.results }}"
  when:
    - item is not skipped
    - item.changed
    - item.challenge_data
    - item.item.cloudflare_api_token is not defined
    - not item.item.use_selfsigned_certificate | default(false)
  become: true

- name: Copy HTTP challenge resources
  ansible.builtin.copy:
    dest: >-
      {{ letsencrypt_nginx_docker_required_volumes.www }}/{{ item.item.domain }}/{{
      item.challenge_data[item.item.csr_common_name
      | default(item.item.domain)]['http-01']['resource'] }}
    content: >-
      {{ item.challenge_data[item.item.csr_common_name
      | default(item.item.domain)]['http-01']['resource_value'] }}
    mode: "0644"
  loop: "{{ letsencrypt_nginx_challenge.results }}"
  register: letsencrypt_nginx_challege_http_resources
  when:
    - item is not skipped
    - item.changed
    - item.challenge_data
    - item.item.cloudflare_api_token is not defined
    - not item.item.use_selfsigned_certificate | default(false)
  become: true

# - ansible.builtin.debug:
#     var: letsencrypt_nginx_challege_http_resources

- name: Complete Letsencrypt challenge
  community.crypto.acme_certificate:
    account_email: "{{ letsencrypt_nginx_account_email }}"
    account_key_src: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/key/public.pem
    acme_directory: "{{ letsencrypt_nginx_acme_directory_url }}"
    acme_version: "{{ letsencrypt_nginx_acme_version }}"
    challenge: >-
      {% if item.item.cloudflare_api_token | default(false) %}dns-01{% else %}http-01{% endif %}
    csr: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/csr/{{
      item.item.csr_common_name | default(item.item.domain)
      | replace('*', '_') }}.csr
    data: "{{ item }}"
    # Set to `force: true` when switching between staging and production
    # force: true
    fullchain_dest: >-
      {{ letsencrypt_nginx_docker_required_volumes.config }}/ssl/crt/{{
      item.item.csr_common_name | default(item.item.domain)
      | replace('*', '_') }}.crt
    remaining_days: "{{ letsencrypt_nginx_remaining_days }}"
    terms_agreed: true
  loop: "{{ letsencrypt_nginx_challenge.results }}"
  register: letsencrypt_nginx_complete_challenge
  when:
    - item is not skipped
    - item.changed
    - not item.item.use_selfsigned_certificate | default(false)
  become: true

# - ansible.builtin.debug:
#     var: letsencrypt_nginx_complete_challenge
