---
# - ansible.builtin.debug:
#     var: letsencrypt_nginx_websites

- name: Initial setup
  tags:
    - letsencrypt
    - nginx
  block:
    - name: Install required packages
      ansible.builtin.import_tasks: apt.yml

    - name: Setup web root directories
      ansible.builtin.import_tasks: www.yml
      tags: www

    - name: Configure basic authentication
      ansible.builtin.import_tasks: basicauth.yml

- name: Let's Encrypt Certificate setup
  tags: letsencrypt
  block:
    - name: Configure SSL certificates
      ansible.builtin.import_tasks: ssl.yml

    - name: Generate initial Nginx configuration
      ansible.builtin.import_tasks: configuration.yml

    - name: Start Nginx for Let's Encrypt validation
      ansible.builtin.import_tasks: docker.yml
      tags: docker

    - name: Obtain Let's Encrypt certificates
      ansible.builtin.import_tasks: letsencrypt.yml

- name: Update Nginx configuration with new certificates
  ansible.builtin.import_tasks: configuration.yml
  notify: Restart nginx
  tags:
    - configuration
    - letsencrypt
    - nginx
