---
- name: Set up website directories
  become: true
  block:
    - name: Ensure .config/git directory exists
      ansible.builtin.file:
        path: "~/.config/git"
        state: directory
        mode: "0755"

    - name: Add .well-known to global gitignore
      ansible.builtin.lineinfile:
        path: "~/.config/git/ignore"
        line: ".well-known/"
        create: true
        mode: "0644"

    - name: Create www directories
      ansible.builtin.file:
        path: "{{ letsencrypt_nginx_docker_required_volumes.www }}/{{ item.domain }}"
        state: directory
        mode: u=rwX,g=rX,o=rX # Directories: 755, Files: 644
        owner: root
        group: root
      loop: "{{ letsencrypt_nginx_websites }}"

    - name: Clone Git repositories
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ letsencrypt_nginx_docker_required_volumes.www }}/{{ item.domain }}"
        version: "{{ item.version | default('HEAD') }}"
        update: true # Always update to latest
        depth: 1
      loop: "{{ letsencrypt_nginx_websites }}"
      register: letsencrypt_nginx_git_clone
      when: item.repo is defined
