---
- name: Configure Let's Encrypt and Nginx
  hosts: webservers
  roles:
    - letsencrypt

- name: Set Let's Encrypt renewal schedule
  hosts: localhost
  tasks:
    - cron:
        name: letsencrypt
        cron_file: /etc/crontab
        user: root
        minute: "1"
        hour: "2"
        job: ansible-playbook {{ playbook_dir }}/letsencrypt.yml
      become: true
