---
- name: Configure Let's Encrypt and Nginx
  hosts: webservers
  roles:
    - letsencrypt

- name: Restart Nginx and set Let's Encrypt renewal schedule
  hosts: localhost
  tasks:
    - service:
        name: nginx
        state: restarted
      become: true

    - cron:
        name: letsencrypt
        cron_file: /etc/crontab
        user: root
        minute: "11"
        hour: "22"
        job: cd {{ playbook_dir }} && ansible-playbook letsencrypt.yml
      become: true
