---
- name: Configure Let's Encrypt and Nginx
  hosts: webservers
  roles:
    - letsencrypt
  tasks:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: true

- name: Set Let's Encrypt renewal schedule
  hosts: localhost
  tasks:
    - cron:
        name: letsencrypt
        cron_file: /etc/crontab
        user: root
        minute: "11"
        hour: "22"
        job: cd {{ playbook_dir }} && ansible-playbook letsencrypt.yml
      become: true
