---
- name: Upgrade all packages
  hosts: all
  tasks:
    - name: Apt autoremove, clean, and dist-upgrade
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        clean: true
        purge: true
        update_cache: true
        upgrade: dist
      become: true

    - name: Gathering package facts
      ansible.builtin.package_facts:

    - name: Upgrade flatpak system packages
      ansible.builtin.command: flatpak --noninteractive --system upgrade
      become: true
      register: flatpak_system_result
      changed_when: "'Nothing to do.' not in flatpak_system_result.stdout"
      when: "'flatpak' in ansible_facts.packages"

    - name: Upgrade flatpak user packages
      ansible.builtin.command: flatpak --noninteractive --user upgrade
      register: flatpak_user_result
      changed_when: "'Nothing to do.' not in flatpak_user_result.stdout"
      when: "'flatpak' in ansible_facts.packages"
