---
- name: Configure Let's Encrypt and Nginx
  hosts: webservers
  roles:
    # Uncomment the `base` and `docker` on the first run
    #- base
    #- docker
    - letsencrypt-nginx
  tags:
    - nginx
    - letsencrypt

- name: Configure Let's Encrypt auto-renewal
  hosts: tron
  tasks:
    - name: Setup renewal cron job
      ansible.builtin.cron:
        name: "Let's Encrypt certificate renewal"
        cron_file: ansible-role-letsencrypt-nginx
        user: root
        minute: "11"
        hour: "22"
        job: >-
          cd {{ playbook_dir }} &&
          ansible-playbook webservers.yml
          >> /var/log/ansible-role-letsencrypt-nginx.log 2>&1
      become: true
