---
- name: Configure Let's Encrypt and Nginx
  hosts: webservers
  roles:
    #- base
    #- msmtp
    - letsencrypt-nginx

- name: Set Let's Encrypt renewal crontab
  hosts: tron
  tasks:
    - cron:
        name: webservers
        cron_file: /etc/crontab
        user: root
        minute: "11"
        hour: "22"
        job: cd {{ playbook_dir }} && ansible-playbook webservers.yml > /dev/null
      become: true
