---
- name: Install Alacritty apt respository
  apt_repository:
    repo: ppa:aslatter/ppa
    update_cache: true
  become: true

- name: Install system packages
  apt:
    name:
      - alacritty
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Register Alacritty alternative
  command: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 50
  become: true

- name: Set Alacritty as default x-terminal-emulator
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/alacritty
  become: true
