---
- name: Install system packages
  ansible.builtin.apt:
    name:
      - alacritty
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Register Alacritty alternative
  ansible.builtin.command:
    cmd: update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/alacritty 50
  become: true
  changed_when: true

- name: Set Alacritty as default x-terminal-emulator
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/alacritty
  become: true
