---
- name: Install system packages
  ansible.builtin.apt:
    name:
      - alacritty
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Set Alacritty as default x-terminal-emulator
  community.general.alternatives:
    name: x-terminal-emulator
    link: /usr/bin/x-terminal-emulator
    path: /usr/bin/alacritty
    priority: 50
  become: true
