---
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - libasound2-dev
    - libcairo2-dev
    - libpulse-dev
    - libx11-xcb-dev
    - libxcb1-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-keysyms1-dev
    - libxcb-randr0-dev
    - libxcb-render-util0-dev
    - libxcb-util0-dev
    - libxcb-xinerama0-dev
    - libxcb-xtest0-dev
    - libxft-dev
    - libxinerama-dev
    - libxpm-dev
    - rofi
    - rxvt-unicode
    - trayer
    - volti
    - xclip
  become: true

- name: Clone BSPWM git repositories
  git:
    repo: "{{ item.repo }}"
    dest: /tmp/{{ item.name }}.git
    version: "{{ item.version }}"
  with_items: "{{ bspwm_projects }}"

- name: Make BSPWM projects
  make:
    chdir: /tmp/{{ item.name }}.git
  with_items: "{{ bspwm_projects  }}"

- name: Make install BSPWM projects
  make:
    chdir: /tmp/{{ item.name }}.git
    target: install
  with_items: "{{ bspwm_projects  }}"
  ignore_errors: yes # Ignore "cp: cannot create regular file ... Text file busy"
  register: r
  become: yes

- name: Copy .desktop file
  copy:
    src: bspwm.desktop
    dest: /usr/share/xsessions/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Ensure that the 'Make install BSPWM projects' play succeeded
  fail: msg="The 'Make install BSPWM projects' play failed"
  when: "item.failed and 'cp: cannot create regular file' not in item.stderr"
  with_items: "{{r.results}}"
