---
# TODO: This fails b/c `apt` actually uses dpkg, which fails with:
# Dependency is not satisfiable: libglib2.0-0 (>= 2.39.4)
# https://github.com/ansible/ansible/issues/77150
#- name: Install Google Chrome
#  apt:
#    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#    dpkg_options: "auto-deconfigure"
#  become: true

- name: "Download google-chrome package (Workaround 1/2)"
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "/tmp/google-chrome-stable.deb"

- name: "Install google-chrome package (Workaround 2/2)"
  command: apt install -qq /tmp/google-chrome-stable.deb
  become: true

- name: "Workaround: Make google-chrome work in Wayland"
  ansible.builtin.replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: "^Exec\\S*=([\/\\w-]*)\\S*(.*)$"
    replace: "Exec=\\1 --ozone-platform-hint=auto \\2"
  become: true
