---
- name: Check if Google Chrome is already installed
  command: dpkg-query -W google-chrome-stable
  register: chrome_check
  failed_when: false
  changed_when: false

- name: Install Google Chrome
  package:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true
  when: chrome_check.rc != 0

- name: Configure Google Chrome for Wayland
  ansible.builtin.replace:
    path: /usr/share/applications/google-chrome.desktop
    regexp: "^Exec\\S*=([\/\\w-]*)\\S*(.*)$"
    replace: "Exec=\\1 --ozone-platform-hint=auto \\2"
  become: true
