---
- name: Install dunst build dependencies
  ansible.builtin.apt:
    name:
      - libdbus-1-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libpango1.0-dev
      - libx11-dev
      - libxdg-basedir-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Build and install dunst
  block:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: desktop_dunst_tmp

    - name: Get releases of dunst
      ansible.builtin.uri:
        url: https://api.github.com/repos/dunst-project/dunst/releases
        return_content: true
      register: desktop_dunst_releases

    - name: Set dunst version to latest stable release
      ansible.builtin.set_fact:
        desktop_dunst_version: >-
          {{ (desktop_dunst_releases.json | selectattr('prerelease', 'equalto', false)
          | selectattr('draft', 'equalto', false) | list | first).tag_name }}

    - name: Download and unarchive dunst {{ desktop_dunst_version }}
      ansible.builtin.unarchive:
        src: "https://github.com/dunst-project/dunst/archive/refs/tags/{{ desktop_dunst_version }}.tar.gz"
        dest: "{{ desktop_dunst_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Build dunst
      community.general.make:
        chdir: "{{ desktop_dunst_tmp.path }}"
      become: true

    - name: Install dunst
      community.general.make:
        chdir: "{{ desktop_dunst_tmp.path }}"
        target: install
      become: true
