---
- name: Install dunst dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libdbus-1-dev
    - libx11-dev
    - libxinerama-dev
    - libxrandr-dev
    - libxss-dev
    - libglib2.0-dev
    - libpango1.0-dev
    - libgtk-3-dev
    - libxdg-basedir-dev
  become: true

- name: Clone dunst git repository
  git:
    repo: "https://github.com/dunst-project/dunst.git"
    dest: /tmp/dunst.git
    version: "HEAD"

- name: Make dunst
  make:
    chdir: /tmp/{{ item.name }}.git
  with_items: "{{ bspwm_projects  }}"
  become: true

- name: Make install dunst
  make:
    chdir: /tmp/dunst.git
    target: install
  become: true
