---
- name: Install dunst build dependencies
  apt:
    name:
      - libdbus-1-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libpango1.0-dev
      - libx11-dev
      - libxdg-basedir-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
    state: latest
  become: true

- name: Check if dunst is already installed
  command: which dunst
  register: dunst_check
  changed_when: false
  failed_when: false

- name: Build and install dunst
  block:
    - name: Clone dunst repository
      git:
        repo: "https://github.com/dunst-project/dunst.git"
        dest: /tmp/dunst.git
        force: yes
      become: true

    - name: Build dunst
      make:
        chdir: /tmp/dunst.git
      become: true

    - name: Install dunst
      make:
        chdir: /tmp/dunst.git
        target: install
      become: true
  when: dunst_check.rc != 0
