---
- name: Install dunst build dependencies
  apt:
    name:
      - libdbus-1-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libpango1.0-dev
      - libx11-dev
      - libxdg-basedir-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Build and install dunst
  block:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: dunst_tmp

    - name: Get the latest version of dunst
      ansible.builtin.uri:
        url: https://api.github.com/repos/dunst-project/dunst/releases/latest
        return_content: true
      register: dunst_version

    - name: Download and unarchive dunst {{ dunst_version.json.tag_name }}
      ansible.builtin.unarchive:
        src: "https://github.com/dunst-project/dunst/archive/refs/tags/{{ dunst_version.json.tag_name }}.tar.gz"
        dest: "{{ dunst_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Build dunst
      make:
        chdir: "{{ dunst_tmp.path }}"
      become: true

    - name: Install dunst
      make:
        chdir: "{{ dunst_tmp.path }}"
        target: install
      become: true