---
- name: Install dunst dependencies
  apt:
    name:
      - libdbus-1-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libpango1.0-dev
      - libx11-dev
      - libxdg-basedir-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxss-dev
    state: latest
  become: true

- name: Clone dunst git repository
  git:
    repo: "https://github.com/dunst-project/dunst.git"
    dest: /tmp/dunst.git
    # Cannot set `depth: 1` or this error is produced:
    # fatal: No names found, cannot describe anything

- name: Make dunst
  make:
    chdir: /tmp/dunst.git
  become: true

- name: Make install dunst
  make:
    chdir: /tmp/dunst.git
    target: install
  become: true
