---
- name: Install eww build dependencies
  apt:
    name:
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
    state: latest
    update_cache: true
  become: true

- name: Build and install eww
  block:
    - name: Clone eww repository
      git:
        repo: "https://github.com/elkowar/eww.git"
        dest: /tmp/eww.git
        depth: 1
        force: yes

    - name: Build eww
      command:
        cmd: cargo build --release --no-default-features --features x11 --features=wayland
        chdir: /tmp/eww.git

    - name: Install eww binary
      ansible.builtin.copy:
        src: /tmp/eww.git/target/release/eww
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: "0755"
      become: true

- name: Configure eww service
  block:
    - name: Install eww.service
      copy:
        dest: /etc/systemd/user/eww.service
        content: |
          [Unit]
          Description=ElKowars wacky widgets
          Documentation=https://elkowar.github.io/eww/
          PartOf=graphical-session.target
          Requires=graphical-session.target
          After=graphical-session.target
          #ConditionEnvironment=WAYLAND_DISPLAY

          [Service]
          Type=exec
          ExecStart=/usr/local/bin/eww daemon --no-daemonize --logs
          ExecStartPost=/usr/local/bin/eww open {{ desktop_eww_bar }}
          Slice=session.slice

          [Install]
          WantedBy=graphical-session.target
      become: true

    - name: Enable eww service
      systemd_service:
        name: eww.service
        daemon_reload: true
        enabled: true
        scope: user
        state: started
