---
- name: Install eww build dependencies
  apt:
    name:
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
      - libgtk-layer-shell-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Build and install eww
  block:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: eww_tmp

    - name: Get the latest version of eww
      ansible.builtin.uri:
        url: https://api.github.com/repos/elkowar/eww/releases/latest
        return_content: true
      register: eww_version

    - name: Download and unarchive eww {{ eww_version.json.tag_name }}
      ansible.builtin.unarchive:
        src: "https://github.com/elkowar/eww/archive/refs/tags/{{ eww_version.json.tag_name }}.tar.gz"
        dest: "{{ eww_tmp.path }}"
        remote_src: true
        extra_opts:
          - --strip-components
          - 1

    - name: Build eww
      command:
        cmd: cargo build --release --no-default-features --features x11 --features=wayland
        chdir: "{{ eww_tmp.path }}"

    - name: Install eww binary
      ansible.builtin.copy:
        src: "{{ eww_tmp.path }}/target/release/eww"
        dest: /usr/local/bin/
        remote_src: true
        owner: root
        group: root
        mode: "0755"
      become: true

- name: Configure eww service
  block:
    - name: Install eww.service
      copy:
        dest: /etc/systemd/user/eww.service
        content: |
          [Unit]
          Description=ElKowars wacky widgets
          Documentation=https://elkowar.github.io/eww/
          PartOf=graphical-session.target
          Requires=graphical-session.target
          After=graphical-session.target
          #ConditionEnvironment=WAYLAND_DISPLAY

          [Service]
          Type=exec
          ExecStart=/usr/local/bin/eww daemon --no-daemonize --logs
          ExecStartPost=/usr/local/bin/eww open {{ desktop_eww_bar }}
          Slice=session.slice

          [Install]
          WantedBy=graphical-session.target
      become: true

    - name: Enable eww service
      systemd_service:
        name: eww.service
        daemon_reload: true
        enabled: true
        scope: user
        state: started
