---
- name: Install eww build dependencies
  ansible.builtin.apt:
    name:
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
      - libgtk-layer-shell-dev
    state: present
    install_recommends: false
    update_cache: true
  become: true

- name: Build and install eww
  block:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: desktop_eww_tmp

    # Install from main branch because the latest stable release (v0.6.0, Aug 2024) is stale
    - name: Clone eww repository (main branch)
      ansible.builtin.git:
        repo: https://github.com/elkowar/eww.git
        dest: "{{ desktop_eww_tmp.path }}"
        version: master
        depth: 1

    # - name: Get releases of eww
    #   ansible.builtin.uri:
    #     url: https://api.github.com/repos/elkowar/eww/releases
    #     return_content: true
    #   register: desktop_eww_releases

    # - name: Set eww version to latest stable release
    #   ansible.builtin.set_fact:
    #     desktop_eww_version: >-
    #       {{ (desktop_eww_releases.json | selectattr('prerelease', 'equalto', false)
    #       | selectattr('draft', 'equalto', false) | list | first).tag_name }}

    # - name: Download and unarchive eww {{ desktop_eww_version }}
    #   ansible.builtin.unarchive:
    #     src: "https://github.com/elkowar/eww/archive/refs/tags/{{ desktop_eww_version }}.tar.gz"
    #     dest: "{{ desktop_eww_tmp.path }}"
    #     remote_src: true
    #     extra_opts:
    #       - --strip-components
    #       - 1

    - name: Build eww
      ansible.builtin.command:
        cmd: cargo build --release --no-default-features --features x11 --features=wayland
        chdir: "{{ desktop_eww_tmp.path }}"
      changed_when: true

    - name: Install eww binary
      ansible.builtin.copy:
        src: "{{ desktop_eww_tmp.path }}/target/release/eww"
        dest: /usr/local/bin/
        remote_src: true
        owner: root
        group: root
        mode: "0755"
      become: true

    - name: Reload eww
      ansible.builtin.systemd_service:
        name: eww.service
        daemon_reload: true
        scope: user
        state: restarted

- name: Configure eww service
  block:
    - name: Install eww.service
      ansible.builtin.copy:
        dest: /etc/systemd/user/eww.service
        mode: "0644"
        content: |
          [Unit]
          Description=ElKowars wacky widgets
          Documentation=https://elkowar.github.io/eww/
          PartOf=graphical-session.target
          Requires=graphical-session.target
          After=graphical-session.target
          #ConditionEnvironment=WAYLAND_DISPLAY

          [Service]
          Type=exec
          ExecStart=/usr/local/bin/eww daemon --no-daemonize --logs
          ExecStartPost=/usr/local/bin/eww open {{ desktop_eww_bar }}
          Slice=session.slice

          [Install]
          WantedBy=graphical-session.target
      become: true

    - name: Enable eww service
      ansible.builtin.systemd_service:
        name: eww.service
        daemon_reload: true
        enabled: true
        scope: user
        state: started
