---
- name: Install eww's build dependencies
  apt:
    name:
      - libdbusmenu-glib-dev
      - libdbusmenu-gtk3-dev
    state: latest
  become: true

- name: Clone eww git repository
  git:
    repo: "https://github.com/elkowar/eww.git"
    dest: /tmp/eww.git
    depth: 1
    force: yes

- name: Build eww
  command:
    cmd: cargo build --release --no-default-features --features x11
    chdir: /tmp/eww.git

- name: Copy eww binary to /usr/local/bin/
  ansible.builtin.copy:
    src: /tmp/eww.git/target/release/eww
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: '0755'
  become: true
