# Apt
- name: Configure Firefox Apt installation method
  block:
    - name: Remove Firefox flatpak if using apt
      community.general.flatpak:
        name: org.mozilla.firefox
        method: user
        state: absent

    - name: Configure Firefox apt packages
      block:
        - name: Add Firefox Next PPA
          apt_repository:
            repo: ppa:mozillateam/firefox-next
            update_cache: true
          become: true

        - name: Configure mozilla PPA priority
          ansible.builtin.copy:
            content: |
              Package: firefox*
              Pin: release o=Ubuntu*
              Pin-Priority: -1
            dest: /etc/apt/preferences.d/firefox-no-snap
          become: true

        - name: Install Firefox and dependencies
          apt:
            name:
              - firefox
              - speech-dispatcher # Required for text-to-speech
            state: latest
          become: true

    - name: Set Firefox as default browser
      command: xdg-settings set default-web-browser firefox.desktop
  when: not desktop_install_firefox_flatpak

# Flatpak
- name: Configure Firefox flatpak installation method
  block:
    - name: Remove and hold Firefox apt package
      block:
        - name: Remove Firefox apt package
          apt:
            name: firefox
            purge: yes
            state: absent
          become: true

        - name: Hold Firefox apt package
          dpkg_selections:
            name: firefox
            selection: hold
          become: true

    - name: Install and configure Firefox flatpak
      block:
        - name: Install Firefox flatpak
          community.general.flatpak:
            name: org.mozilla.firefox
            method: user

        - name: Configure Firefox cursor theme
          command: flatpak override --user --env=XCURSOR_THEME=Adwaita org.mozilla.firefox

    - name: Set Firefox as default browser
      command: xdg-settings set default-web-browser org.mozilla.firefox.desktop
  when: desktop_install_firefox_flatpak
