---
- name: Pin default Firefox snap package
  copy:
    content: "Package: firefox*\nPin: release o=Ubuntu*\nPin-Priority: -1"
    dest: /etc/apt/preferences.d/firefox-no-snap
    owner: root
    group: root
    mode: '0644'
  become: true
  register: no_snap
  when: ansible_distribution_version is version('22.04', '>=')

- name: Remove firefox package
  apt:
    name: firefox
    state: absent
    purge: yes
  become: true
  when: no_snap.changed

- name: Remove firefox snap
  community.general.snap:
    name: firefox
    state: absent
  when: no_snap.changed
  become: true

- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  apt_repository:
    repo: ppa:mozillateam/ppa
    update_cache: yes
  become: true
  when: no_snap.changed

- name: Install firefox package from PPA
  apt:
    name: firefox
    state: latest
  become: true
  when: no_snap.changed
