---
- name: Install system fonts
  block:
    - name: Install font packages
      apt:
        name:
          - fonts-dejavu
          - fonts-hack
          - fonts-ubuntu-console
          - ttf-mscorefonts-installer
          - xfonts-terminus
        state: latest
        install_recommends: false
        update_cache: true
      become: true

    - name: Configure Microsoft fonts
      block:
        - name: Accept mscorefonts EULA
          debconf:
            name: ttf-mscorefonts-installer
            question: msttcorefonts/accepted-mscorefonts-eula
            vtype: select
            value: "true"
          become: true

        - name: Install mscorefonts
          apt:
            name: ttf-mscorefonts-installer
            state: latest
            install_recommends: false
          notify: Update font cache
          become: true

- name: Install Source Code Pro font
  block:
    - name: Get latest Source Code Pro release
      uri:
        url: https://api.github.com/repos/adobe-fonts/source-code-pro/releases/latest
        return_content: true
      register: source_code_pro_release

    - name: Set Source Code Pro download URL fact
      set_fact:
        source_code_pro_url: "{{ (source_code_pro_release.json.assets | selectattr('name', 'match', '.*TTF.*.zip') | first).browser_download_url }}"

    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/source-code-pro
        state: directory

    - name: Download and extract Source Code Pro package
      unarchive:
        src: "{{ source_code_pro_url }}"
        dest: /tmp/source-code-pro/
        remote_src: true
        creates: /tmp/source-code-pro/LICENSE.md

    - name: Install Source Code Pro font files
      copy:
        src: /tmp/source-code-pro/
        dest: /usr/share/fonts/truetype/source-code-pro
        remote_src: true
      delegate_to: "{{ inventory_hostname }}"
      notify: Update font cache
      become: true