---
- name: Install system fonts
  block:
    - name: Install font packages
      ansible.builtin.apt:
        name:
          - fonts-dejavu
          - fonts-hack
          - fonts-ubuntu-console
          - ttf-mscorefonts-installer
          - xfonts-terminus
        state: latest
        install_recommends: false
        update_cache: true
      become: true

    - name: Configure Microsoft fonts
      block:
        - name: Accept mscorefonts EULA
          ansible.builtin.debconf:
            name: ttf-mscorefonts-installer
            question: msttcorefonts/accepted-mscorefonts-eula
            vtype: select
            value: "true"
          become: true

        - name: Install mscorefonts
          ansible.builtin.apt:
            name: ttf-mscorefonts-installer
            state: latest
            install_recommends: false
          notify: Update font cache
          become: true

- name: Install Source Code Pro font
  block:
    - name: Get releases of Source Code Pro
      ansible.builtin.uri:
        url: https://api.github.com/repos/adobe-fonts/source-code-pro/releases
        return_content: true
      register: desktop_source_code_pro_releases

    - name: Set Source Code Pro to latest stable release
      ansible.builtin.set_fact:
        desktop_source_code_pro_release: "{{ desktop_source_code_pro_releases.json | selectattr('prerelease', 'equalto', false) | selectattr('draft', 'equalto', false) | first }}" # noqa: yaml[line-length]

    - name: Set Source Code Pro download URL fact
      ansible.builtin.set_fact:
        desktop_source_code_pro_url: >-
          {{ desktop_source_code_pro_release.assets
          | selectattr('name', 'match', '.*TTF.*.zip')
          | map(attribute='browser_download_url') | first }}

    - name: Create temporary directory
      ansible.builtin.file:
        path: /tmp/source-code-pro
        state: directory
        mode: "0755"

    - name: Download and extract Source Code Pro package
      ansible.builtin.unarchive:
        src: "{{ desktop_source_code_pro_url }}"
        dest: /tmp/source-code-pro/
        remote_src: true
        creates: /tmp/source-code-pro/LICENSE.md

    - name: Install Source Code Pro font files
      ansible.builtin.copy:
        src: /tmp/source-code-pro/TTF/
        dest: /usr/share/fonts/truetype/source-code-pro/
        remote_src: true
        mode: "0644"
        directory_mode: "0755"
      notify: Update font cache
      become: true
