---
- name: Configure GRUB settings
  block:
    - name: Show GRUB menu
      lineinfile:
        path: /etc/default/grub
        regexp: '^#?GRUB_TIMEOUT_STYLE\s*='
        line: "GRUB_TIMEOUT_STYLE=menu"
      become: true

    - name: Set GRUB timeout to 3 seconds
      lineinfile:
        path: /etc/default/grub
        regexp: '^#?GRUB_TIMEOUT\s*='
        line: "GRUB_TIMEOUT=3"
      become: true

    - name: Enable Thinkpad touchpad scrolling
      lineinfile:
        path: /etc/default/grub
        regexp: '^#?GRUB_CMDLINE_LINUX_DEFAULT\s*='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="psmouse.synaptics_intertouch=0"'
      become: true

  notify: Update GRUB
