---
- name: Install Insync apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C
  become: true

- name: Install Insync apt respository
  apt_repository:
    repo: deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib
    update_cache: yes
  become: true

- name: Install Insync system package
  apt:
    name: insync
    state: latest
  become: true
