---
- name: Configure Insync repository
  block:
    - name: Add Insync apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: ACCAF35C
      become: true

    - name: Add Insync apt repository
      apt_repository:
        repo: deb http://apt.insync.io/ubuntu {{ ansible_distribution_release }} non-free contrib
        update_cache: true
      become: true

- name: Install and configure Insync
  become: true
  block:
    - name: Install Insync package
      apt:
        name: insync
        state: latest
        install_recommends: false

    - name: Fix Wayland compatibility
      # Workaround error when starting insync in Wayland (niri window manager):
      # QSocketNotifier: Can only be used with threads started with QThread
      # /usr/lib/insync/insync: symbol lookup error: /opt/amdgpu/lib/x86_64-linux-gnu/libEGL_mesa.so.0:
      # undefined symbol: wl_display_create_queue_with_name
      ansible.builtin.file:
        path: /usr/lib/insync/libwayland-client.so.0
        state: absent

    - name: Write insync.desktop with Wayland compatibility fix
      copy:
        content: |
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Insync
          GenericName=Insync
          Comment=Launch Insync
          Icon=insync
          Categories=Network;
          # https://forums.insynchq.com/t/insync-3-9-4-fails-to-load-on-ubuntu-24-04-2-lts-addressed/36032/5
          Exec=insync start --qt-qpa-platform=xcb
          TryExec=insync
          Terminal=false
        dest: /usr/share/applications/insync.desktop
        mode: "0644"
