---
- name: Install LACT
  block:
    - name: Get latest LACT release
      ansible.builtin.include_tasks: get_latest_github_release.yml
      vars:
        github_release_repo: ilya-zlobintsev/LACT
        github_release_fact: desktop_lact_release

    - name: Set LACT download URL fact
      ansible.builtin.set_fact:
        desktop_lact_download_url: >-
          {{ desktop_lact_release.assets
          | selectattr('name', 'match', 'lact-.*\.amd64\.ubuntu-' ~
          (ansible_facts["distribution_version"] | replace('.', '')) ~ '\.deb')
          | rejectattr('name', 'match', 'lact-headless-.*')
          | map(attribute='browser_download_url') | first }}

    - name: Install LACT package
      ansible.builtin.apt:
        deb: "{{ desktop_lact_download_url }}"
        install_recommends: false
        update_cache: true
      become: true
