---
- name: Install and configure lemurs display manager
  block:
    - name: Install lemurs dependencies
      apt:
        name:
          - build-essential
          - curl
          - libpam0g-dev
          - libxcb-xkb-dev
          - libxcb1-dev
          - pkg-config
        state: latest
        install_recommends: false
        update_cache: true
      become: true

    - name: Install lemurs
      block:
        - name: Create a temporary directory
          ansible.builtin.tempfile:
            state: directory
          register: lemurs_tmp

        - name: Get the latest version of lemurs
          ansible.builtin.uri:
            url: https://api.github.com/repos/coastalwhite/lemurs/releases/latest
            return_content: true
          register: lemurs_version

        - name: Download lemurs binary {{ lemurs_version.json.tag_name }}
          get_url:
            url: "https://github.com/coastalwhite/lemurs/releases/download/{{ lemurs_version.json.tag_name }}/lemurs-x86_64-unknown-linux-gnu.tar.xz"
            dest: "{{ lemurs_tmp.path }}/lemurs.tar.xz"

        - name: Extract lemurs binary
          unarchive:
            src: "{{ lemurs_tmp.path }}/lemurs.tar.xz"
            dest: "{{ lemurs_tmp.path }}"
            remote_src: true

        - name: Install lemurs binary
          copy:
            src: "{{ lemurs_tmp.path }}/lemurs-x86_64-unknown-linux-gnu/lemurs"
            dest: /usr/local/bin/lemurs
            mode: "0755"
            remote_src: true
          become: true

    - name: Configure lemurs
      block:
        - name: Create lemurs configuration directory
          file:
            path: /etc/lemurs
            state: directory
            mode: "0755"
          become: true

        - name: Download default lemurs configuration
          get_url:
            url: "https://raw.githubusercontent.com/coastalwhite/lemurs/{{ lemurs_version.json.tag_name }}/extra/config.toml"
            dest: "/etc/lemurs/config.toml"
            mode: "0644"
          become: true

        - name: Override configuration settings
          lineinfile:
            path: /etc/lemurs/config.toml
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
          loop:
            - {
                regexp: '^xsessions_path\s*=.*',
                line: 'xsessions_path = "/usr/local/share/xsessions"',
              }
            - {
                regexp: '^wayland_sessions_path\s*=.*',
                line: 'wayland_sessions_path = "/usr/local/share/wayland-sessions"',
              }
            - {
                regexp: '^system_shell\s*=.*',
                line: 'system_shell = "/bin/bash"',
              }
          become: true

        - name: Download lemurs systemd service
          get_url:
            url: "https://raw.githubusercontent.com/coastalwhite/lemurs/{{ lemurs_version.json.tag_name }}/extra/lemurs.service"
            dest: /usr/lib/systemd/system/lemurs.service
            mode: "0644"
          become: true

        - name: Update ExecStart path in service file
          lineinfile:
            path: /usr/lib/systemd/system/lemurs.service
            regexp: '^ExecStart\s*=.*'
            line: "ExecStart=/usr/local/bin/lemurs"
          become: true

        - name: Download xsetup.sh script
          get_url:
            url: "https://raw.githubusercontent.com/coastalwhite/lemurs/{{ lemurs_version.json.tag_name }}/extra/xsetup.sh"
            dest: /etc/lemurs/xsetup.sh
            mode: "0755"
          become: true

        # TODO: Superceded by the copy below
        # - name: Download lemurs.pam file
        #   get_url:
        #     url: "https://raw.githubusercontent.com/coastalwhite/lemurs/{{ lemurs_version.json.tag_name }}/extra/lemurs.pam"
        #     dest: /etc/pam.d/lemurs
        #     mode: "0644"
        #   become: true

        - name: Copy lemurs.pam file to /etc/pam.d/lemurs
          copy:
            src: lemurs.pam
            dest: /etc/pam.d/lemurs
            mode: "0644"
          become: true

    - name: Configure system integration
      block:
        - name: Prevent TTY conflicts
          systemd_service:
            name: getty@tty2.service
            daemon_reload: true
            state: stopped
            enabled: false
          become: true

        - name: Enable lemurs display manager
          systemd_service:
            name: lemurs.service
            daemon_reload: true
            enabled: true
            masked: false
          become: true
