---
- name: Disable other display manager services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: no
  ignore_errors: yes
  with_items:
    - gdm3
    - ly
    - display-manager
  become: true

- name: Uninstall other display managers
  apt:
    name:
      - gdm3
      - ly
    state: absent
  become: true

- name: Install lightdm
  apt:
    name: lightdm
    state: present
  become: true

- name: Enable lightdm.service
  systemd:
    name: lightdm
    daemon_reload: yes
    enabled: yes
  become: true
