---
- name: Install system packages
  apt:
    name:
      - adwaita-icon-theme-full
      - audacity
      - desktop-file-utils
      - feh
      - filezilla
      - firefox
      - fonts-dejavu
      - fonts-hack
      - fonts-ubuntu-console
      - gimp
      - gnome-disk-utility
      - gnome-keyring
      - gnome-screensaver
      - gnome-themes-standard
      - gtk-theme-switch
      - gtk2-engines
      - gtk2-engines-murrine
      - gtk2-engines-pixbuf
      - hsetroot
      - inkscape
      - intltool
      - libc6
      - libcairo2
      - libglib2.0-0
      - libglib2.0-dev
      - libgtk2.0-0
      - libgtk2.0-bin
      - libgtk2.0-dev
      - libpango-1.0-0
      - libreoffice
      - libsecret-1-0
      - libsecret-tools
      - libudev-dev
      - libudev1
      - libx11-6
      - pavucontrol
      - pcmanfm
      - pkg-config
      - redshift-gtk
      - scrot
      - shared-mime-info
      - software-properties-gtk
      - solaar
      - suckless-tools
      - ttf-mscorefonts-installer
      - ubuntu-drivers-common
      - udevil
      - usb-creator-gtk
      - vlc
      - wireshark
      - x11-xserver-utils
      - xautolock
      - xclip
      - xcompmgr
      - xdotool
      - xfonts-terminus
      - xorg
      - xsel
      - xss-lock
      - xul-ext-calendar-timezones
      - xul-ext-lightning
    state: latest
    update_cache: yes
  become: true

- name: Install binary drivers
  command: ubuntu-drivers autoinstall
  become: true

- name: Set default printer paper size
  command: paperconfig -p letter
  become: true

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- import_tasks: alacritty.yml

- import_tasks: dconf.yml

- import_tasks: dimpl.yml

- import_tasks: dunst.yml

- import_tasks: grub.yml

- include_tasks: insync.yml
  when: desktop_install_insync

- import_tasks: lightdm.yml
  when: not desktop_install_ly_instead_of_lightdm

- import_tasks: ly.yml
  when: desktop_install_ly_instead_of_lightdm

- import_tasks: mscorefonts.yml

- import_tasks: source-code-pro.yml
