---
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - adwaita-icon-theme-full
    - audacity
    - dconf-tools
    - desktop-file-utils
    - feh
    - filezilla
    - firefox
    - gimp
    - gksu
    - gnome-control-center
    - gnome-disk-utility
    - gnome-keyring
    - gnome-themes-standard
    - gtk-redshift
    - gtk-theme-switch
    - gtk2-engines
    - gtk2-engines-murrine
    - gtk2-engines-pixbuf
    - hsetroot
    - inkscape
    - intltool
    - libc6
    - libcairo2
    - libglib2.0-0
    - libglib2.0-dev
    - libgtk2.0-0
    - libgtk2.0-bin
    - libgtk2.0-dev
    - libpango1.0-0
    - libreoffice
    - libsecret-1-0
    - libsecret-tools
    - libudev-dev
    - libudev1
    - libx11-6
    - lightdm
    - pkg-config
    - python-psutil
    - scrot
    - shared-mime-info
    - software-properties-gtk
    - solaar
    - spacefm
    - suckless-tools
    - thunderbird
    - ttf-dejavu
    - ttf-mscorefonts-installer
    - udevil
    - usb-creator-gtk
    - vlc
    - wireshark
    - x11-xserver-utils
    - xautolock
    - xcompmgr
    - xdotool
    - xfce4-power-manager
    - xfonts-terminus
    - xorg
    - xss-lock
    - xul-ext-calendar-timezones
    - xul-ext-lightning
  become: true

- name: Install binary drivers
  command: ubuntu-drivers autoinstall
  become: true

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- import_tasks: dconf.yml

- import_tasks: dimpl.yml

- import_tasks: dunst.yml

- include_tasks: insync.yml
  when: desktop_install_insync

- import_tasks: spotify.yml

- import_tasks: mscorefonts.yml

- import_tasks: source-code-pro.yml
