---
- import_tasks: dependencies.yml

- name: Configure display manager
  block:
    - import_tasks: lightdm.yml
      when: not desktop_install_ly_instead_of_lightdm
      tags: [display-manager]

    - import_tasks: ly.yml
      when: desktop_install_ly_instead_of_lightdm
      tags: [display-manager]

- name: Configure system applications
  block:
    - import_tasks: alacritty.yml

    - import_tasks: chrome.yml

    - import_tasks: dconf.yml

    - import_tasks: dunst.yml

    - import_tasks: eww.yml

    - import_tasks: firefox.yml

    - import_tasks: flatpak.yml

    - import_tasks: fonts.yml

    - import_tasks: grub.yml

    - import_tasks: insync.yml
      when: desktop_install_insync

    - import_tasks: lact.yml

    - import_tasks: pavolume.yml

    - import_tasks: rofi.yml
