---
- name: Install system packages
  apt:
    name:
      - audacity
      - blueman
      - desktop-file-utils
      - feh
      - filezilla
      - gimp
      - gnome-disk-utility
      - gnome-keyring
      - gnome-screensaver
      - hsetroot
      - inkscape
      - intltool
      - libc6
      - libcairo2
      - libglib2.0-0
      - libglib2.0-dev
      - libgtk2.0-0
      - libgtk2.0-bin
      - libgtk2.0-dev
      - libpango-1.0-0
      - libreoffice
      - libsecret-1-0
      - libsecret-tools
      - libudev-dev
      - libudev1
      - libx11-6
      - lxappearance
      - network-manager-gnome
      - pavucontrol
      - pcmanfm
      - pkg-config
      #- redshift-gtk
      - scrot
      - shared-mime-info
      - software-properties-gtk
      # Solaar is used to manage logitech receivers
      #- solaar
      - suckless-tools
      - ubuntu-drivers-common
      - udevil
      - usb-creator-gtk
      - vlc
      - wireshark
      - x11-xserver-utils
      - xautolock
      - xclip
      - xcompmgr
      - xdotool
      - xorg
      - xsel
      - xss-lock
      - xul-ext-calendar-timezones
      - xul-ext-lightning
    install_recommends: no
    state: latest
    update_cache: yes
  become: true


- name: Install binary drivers
  command: ubuntu-drivers autoinstall
  become: true

- name: Set default printer paper size
  command: paperconfig -p letter
  become: true

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: true

- import_tasks: alacritty.yml

- import_tasks: dconf.yml

- import_tasks: dunst.yml

- import_tasks: eww.yml

- import_tasks: firefox.yml
