---
- name: Install pavolume build dependencies
  ansible.builtin.apt:
    name: libpulse-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Build and install pavolume
  block:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
      register: desktop_pavolume_tmp

    - name: Clone pavolume git repository
      ansible.builtin.git:
        repo: "https://github.com/andornaut/pavolume.git"
        dest: "{{ desktop_pavolume_tmp.path }}"
        depth: 1
        version: main

    - name: Build pavolume
      community.general.make:
        chdir: "{{ desktop_pavolume_tmp.path }}"

    - name: Install pavolume
      community.general.make:
        chdir: "{{ desktop_pavolume_tmp.path }}"
        target: install
      register: desktop_pavolume_install
      failed_when:
        - desktop_pavolume_install.failed
        - "'cp: cannot create regular file' not in desktop_pavolume_install.stderr"
      become: true
  always:
    - name: Remove the temporary directory
      ansible.builtin.file:
        path: "{{ desktop_pavolume_tmp.path }}"
        state: absent
      when: desktop_pavolume_tmp.path is defined
      become: true
