---
- name: Clone pavolume git repository
  ansible.builtin.git:
    repo: "https://github.com/andornaut/pavolume.git"
    dest: /tmp/pavolume.git
    depth: 1
    force: true
    version: main

- name: Make pavolume
  community.general.make:
    chdir: /tmp/pavolume.git

- name: Make install pavolume
  community.general.make:
    chdir: /tmp/pavolume.git
    target: install
  register: desktop_pavolume_install
  failed_when:
    - desktop_pavolume_install.failed
    - "'cp: cannot create regular file' not in desktop_pavolume_install.stderr"
  become: true
