---
- name: Install system packages
  ansible.builtin.apt:
    name:
      - bison
      - flex
      - libxcb-cursor-dev
      - libstartup-notification0-dev
      - libxkbcommon-x11-dev
      - ninja-build
    state: present
    install_recommends: false
    update_cache: true
  become: true

- name: Install meson (versioned package on noble)
  ansible.builtin.apt:
    name: meson-1.5
    state: present
    install_recommends: false
  become: true
  when: ansible_facts['distribution_version'] is version('25.04', '<')

- name: Install meson
  ansible.builtin.apt:
    name: meson
    state: present
    install_recommends: false
  become: true
  when: ansible_facts['distribution_version'] is version('25.04', '>=')

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: desktop_rofi_tmp

# Fork of rofi that supports Wayland:
# https://github.com/lbonn/rofi?tab=readme-ov-file#wayland-support
- name: Get releases of rofi
  ansible.builtin.uri:
    url: https://api.github.com/repos/lbonn/rofi/releases
    return_content: true
  register: desktop_rofi_releases

- name: Set rofi version to latest stable release
  ansible.builtin.set_fact:
    desktop_rofi_version: >-
      {{ (desktop_rofi_releases.json | selectattr('prerelease', 'equalto', false)
      | selectattr('draft', 'equalto', false) | list | first).tag_name }}

- name: Download and unarchive rofi
  ansible.builtin.unarchive:
    src: "https://github.com/lbonn/rofi/releases/download/{{ desktop_rofi_version }}/rofi-{{ desktop_rofi_version }}.tar.xz"
    dest: "{{ desktop_rofi_tmp.path }}"
    remote_src: true
    extra_opts:
      - --strip-components
      - 1

- name: Configure rofi build
  ansible.builtin.command:
    cmd: meson setup build
    chdir: "{{ desktop_rofi_tmp.path }}"
  changed_when: true

- name: Build rofi
  ansible.builtin.command:
    cmd: ninja -C build
    chdir: "{{ desktop_rofi_tmp.path }}"
  changed_when: true

- name: Install rofi
  ansible.builtin.command:
    cmd: ninja -C build install
    chdir: "{{ desktop_rofi_tmp.path }}"
  become: true
  changed_when: true
