---
- name: Add Spotify apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  become: true

- name: Add Spotify apt respository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    update_cache: yes
  become: true

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest
  become: true

