---
- name: Install system packages
  apt:
    name:
      - apache2-utils
      - python3-openssl
      - python3-passlib
      - ssl-cert
    state: latest
    install_recommends: false
    update_cache: true
  become: true
