---
- name: Create basicauth directory
  file:
    path: "{{ letsencryptnginx_docker_required_volumes.config }}/basicauth"
    state: directory
  become: true

- name: Configure basicauth .htpasswd files
  htpasswd:
    path: "{{ letsencryptnginx_docker_required_volumes.config }}/basicauth/{{ item.0.domain }}.htpasswd"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    mode: "0644"
  when: item.1 is defined
  with_subelements:
    - "{{ letsencryptnginx_websites }}"
    - credentials
    - skip_missing: True
  become: true

- name: Configure HTTP Basic Authentication for aliases
  htpasswd:
    path: "{{ letsencryptnginx_docker_required_volumes.config }}/basicauth/{{ item.0.file_basename }}.htpasswd"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    mode: "0644"
  when: item.1 is defined
  with_subelements:
    - "{{ letsencryptnginx_websites | selectattr('aliases','defined') | map(attribute='aliases') | flatten }}"
    - credentials
    - skip_missing: True
  become: true
