---
- name: Ensure Docker volume directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: root
    group: root
    recurse: yes
  loop:
    - "{{ letsencryptnginx_docker_required_volumes.config }}"
    - "{{ letsencryptnginx_docker_required_volumes.www }}"
  become: true

- name: Start Nginx Docker container
  vars:
    required_volumes:
      - "{{ letsencryptnginx_docker_required_volumes.config }}:/etc/nginx/conf.d:ro"
      - "{{ letsencryptnginx_docker_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ letsencryptnginx_docker_required_volumes.www }}:/var/www:ro"
      - /var/cache/nginx
      - /var/run
  community.docker.docker_compose_v2:
    project_name: nginx
    pull: always
    definition:
      services:
        nginx:
          container_name: nginx
          image: "{{ letsencryptnginx_docker_image }}"
          network_mode: host
          restart: unless-stopped
          volumes: "{{ required_volumes + letsencryptnginx_docker_extra_volumes }}"
  become: true
