---
#- ansible.builtin.debug:
#      var: letsencryptnginx_websites

- name: Initial setup
  block:
    - name: Install required packages
      import_tasks: apt.yml

    - name: Setup web root directories
      import_tasks: www.yml

    - name: Configure basic authentication
      import_tasks: basicauth.yml
  tags:
    - letsencrypt
    - nginx

- name: Let's Encrypt Certificate setup
  block:
    - name: Configure SSL certificates
      import_tasks: ssl.yml

    - name: Generate initial Nginx configuration
      import_tasks: configuration.yml

    - name: Start Nginx for Let's Encrypt validation
      import_tasks: docker.yml
      tags: docker

    - name: Obtain Let's Encrypt certificates
      import_tasks: letsencrypt.yml
  tags: letsencrypt

- name: Update Nginx configuration with new certificates
  import_tasks: configuration.yml
  notify: Restart nginx
  tags:
    - letsencrypt
    - nginx
