---
- name: Set up website directories
  block:
    - name: Create www directories
      file:
        path: "{{ letsencryptnginx_docker_required_volumes.www }}/{{ item.domain }}"
        state: directory
        mode: "2755" # Allow read/execute for web server
        owner: root
        group: root
      loop: "{{ letsencryptnginx_websites }}"

    - name: Clone Git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ letsencryptnginx_docker_required_volumes.www }}/{{ item.domain }}"
        depth: 1
        force: yes
        version: "{{ item.version|default('HEAD') }}"
        update: yes # Always update to latest
      loop: "{{ letsencryptnginx_websites }}"
      register: git_clone
      when: item.repo is defined

    - name: Run website commands
      shell: "{{ item.command }}"
      args:
        chdir: "{{ letsencryptnginx_docker_required_volumes.www }}/{{ item.domain }}"
        executable: /bin/bash
      loop: "{{ git_clone.results }}"
      when:
        - item is not skipped
        - item.changed
        - item.command is defined
  become: true
