---
- name: Set up website directories
  block:
    - name: Ensure .config/git directory exists
      file:
        path: "~/.config/git"
        state: directory
        mode: "0755"

    - name: Add .well-known to global gitignore
      lineinfile:
        path: "~/.config/git/ignore"
        line: ".well-known/"
        create: yes

    - name: Create www directories
      file:
        path: "{{ letsencryptnginx_docker_required_volumes.www }}/{{ item.domain }}"
        state: directory
        mode: u=rwX,g=rX,o=rX # Directories: 755, Files: 644
        owner: root
        group: root
      loop: "{{ letsencryptnginx_websites }}"

    - name: Clone Git repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ letsencryptnginx_docker_required_volumes.www }}/{{ item.domain }}"
        version: "{{ item.version|default('HEAD') }}"
        update: true # Always update to latest
        depth: 1
      loop: "{{ letsencryptnginx_websites }}"
      register: git_clone
      when: item.repo is defined
  become: true
