#!/bin/bash

set -e

[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }

RETENTION="{{ nas_backup_directories_retention }}"

if [[ $# -eq 4 ]]; then
    name="${1}"
    device="${2}"
    key_file="${3}"
    backup_dir="${4}"
elif [[ $# -eq 0 ]]; then
    name=backup
    device="{{ nas_usb_device }}"
    key_file="{{ nas_usb_key_file }}"
    backup_dir="{{ nas_backup_directory }}"
else
    echo "Usage: $(basename "${0}") backup /dev/usb /luks/key/file /media/nas/backups">&2
    exit 1
fi

mount_dir="$(mktemp -d)"

is_mapped() {
	cryptsetup status ${name} >/dev/null
}

open_luks() {
	cryptsetup --key-file ${key_file} luksOpen ${device} ${name}
}

is_mapped || open_luks || { echo 'Failed to open luks device'>&2; exit 1; }
mount -t ext4 /dev/mapper/${name} ${mount_dir}

# eg. /tmp/tmp.xxx/backup.2018-12-30
target_dir="${mount_dir}/$(date -d @$(stat --format=%Y "${backup_dir}") +backup.%Y-%m-%d)"

mkdir -p "${target_dir}"

# Delete backup dirs other than the ${RETENTION_NUMBER} newest
ls -1p "${mount_dir}" | \
    grep -P '^backup\.\d{4}-\d{2}-\d{2}/$' | \
    head -n-${RETENTION} | \
    xargs -I {} rm -rf -- {}

rsync --archive --delete --quiet "${backup_dir}" "${target_dir}"
