#!/bin/bash

set -eu -o nounset

[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }

RETENTION_NUMBER="{{ nas_backup_directories_retention }}"
RETRY_SECS=10

if [[ $# -eq 0 ]]; then
    deviceName=nasbackup
    sourceDir="{{ nas_backup_directory }}"
elif [[ $# -eq 2 ]]; then
    deviceName="${1}"
    sourceDir="${2}"
else
    echo "Usage: $(basename "${0}") nasbackup /media/nas/backups">&2
    exit 1
fi

[[ -d "${sourceDir}" ]] || { echo "Backup dir does not exist: ${sourceDir}">&2; exit 1; }

closeLuks() {
    mount_dirs="$(findmnt -rno TARGET "/dev/mapper/${deviceName}")" || true
    if [[ -n "${mount_dirs}" ]]; then
        echo "Unmounting: ${mount_dirs}"
        for mountDir in "${mount_dirs}"; do
        if ! umount "${mountDir}"; then
            echo "Sleeping for ${RETRY_SECS} seconds"
            sleep ${RETRY_SECS}
            umount "${mountDir}"
        fi
        done
    fi
    cryptdisks_stop ${deviceName}
}

# Derive mountpoint. This is only useful when running with non-default args, b/c the default case could just use
# {{ nas_backup_mount_directory }}
mount "/dev/mapper/${deviceName}" || true
if mountDir="$(findmnt -rno TARGET "/dev/mapper/${deviceName}")"; then
    # It may be mounted to multiple mount points, so take the first one.
    mountDir="$(echo -n "${mountDir}"|head -1)"
fi

if [[ -z "${mountDir}" ]]; then
	echo 'Could not derive $mountDir' >2
	exit 1
fi

echo \# How to mount:
echo systemctl start ${mountDir}
echo \# How to unmount:
echo umount ${mountDir}
echo cryptdisks_stop ${deviceName}
echo ---

# eg. /media/nasbackup/backup.2020-04-30
destDir="${mountDir}/$(date -d @$(stat --format=%Y "${sourceDir}") +backup.%Y-%m-%d)"
echo "Device mounted to: ${mountDir}"
echo "Backup source: ${sourceDir}"
echo "Backup destination: ${destDir}"
echo ---

mkdir -p "${destDir}"

echo Deleting backups older than the last ${RETENTION_NUMBER}
ls -1p "${mountDir}" | \
    grep -P '^backup\.\d{4}-\d{2}-\d{2}/$' | \
    head -n-${RETENTION_NUMBER} | \
    xargs -I {} rm -rf -- "${mountDir}/{}"

echo "Starting backup..."
rsync --archive --delete --human-readable --info=progress2 "${sourceDir}" "${destDir}"
echo Done
tree -L 2 "${mountDir}"
echo ---
closeLuks

