#!/bin/bash

set -e

if [[ $# -eq 6 ]]; then
    name_a="${1}"
    device_a="${2}"
    name_b="${3}"
    device_b="${4}"
    key_file="${5}"
    mount_dir="${6}"
elif [[ $# -eq 0 ]]; then
    name_a=nas-raid1-a
    device_a="{{ nas_device_raid1_a }}"
    name_b=nas-raid1-b
    device_b="{{ nas_device_raid1_b }}"
    key_file="{{ nas_key_file }}"
    mount_dir="{{ nas_mount_directory }}"
else
    echo "Usage: $(basename "${0}") luksNameA /dev/sda luksNameB /dev/sdb /luks/key/file /media/nas">&2
    exit 1
fi

mount_device="/dev/mapper/${name_a}"

if [[ "$(findmnt -rno SOURCE "${mount_dir}")" == "${mount_device}" ]]; then
    # Already mounted
    exit
fi

[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }
[[ ! "$(ls -A "${mount_dir}")" ]] || { echo "Mount dir must be empty: ${mount_dir}">&2; exit 1; }

openluks "${name_a}" "${device_a}" "${key_file}"
openluks "${name_b}" "${device_b}" "${key_file}"

mount \
    -t btrfs "${mount_device}" \
    -o device=/dev/mapper/${name_a},device=/dev/mapper/${name_b} \
    ${mount_dir}
