---
- name: Enable i386 architecture repositories (for Steam)
  command: dpkg --add-architecture i386
  become: true

- name: Accept Steam EULA
  debconf:
    name: steam
    question: steam/question
    vtype: select
    value: "I AGREE"
  become: true

# Key is not available on disco
#- name: Install Lutris apt key
#  apt_key:
#    url: "https://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ ansible_distribution_version }}/Release.key"
#    state: present
#  become: true

- name: Install Lutris apt repository
  apt_repository:
    repo: "ppa:lutris-team/lutris"
    state: present
    update_cache: yes
  become: true

- name: Install system packages
  apt:
    name:
      - higan
      - libasound2-plugins:i386 # Workaround for Guild Wars 2 audio in CrossOver
      - lutris
      - steam
      # Libs used by Steam games
      - libbz2-1.0:i386
      - libgdk-pixbuf2.0-0:i386
      - libgtk2.0-0:i386
      - libva-x11-1:i386
      - libva1:i386
      - libvdpau1:i386
      - libxtst6:i386
    state: latest
    update_cache: yes
  become: true
