---
- name: Install system packages
  apt:
    name:
      #- 2048-qt
      #- bsdgames

      # For `chdman` to create .chd archives
      - mame-tools
    install_recommends: false
    state: latest
    update_cache: true
  become: true

- import_tasks: flatpak.yml
