---
- name: Enable i386 architecture repositories (for Steam)
  command: dpkg --add-architecture i386
  become: true

- name: Accept Steam EULA
  debconf:
    name: steam
    question: steam/question
    vtype: select
    value: "I AGREE"
  become: true

  #TODO Install Lutris, install 32bit libs: 
  # libxtst6:i386 libgdk-pixbuf2.0-0:i386 libgtk2.0-0:i386 
  # libva1:i386 libva-x11-1:i386 libbz2-1.0:i386 libvdpau1:i386 

- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - higan
  - libasound2-plugins:i386 # Workaround for Guild Wars 2 audio in CrossOver
  - steam
  become: true
