---
- name: Install system packages
  apt:
    name:
      - 2048-qt
      - bsdgames
    state: latest
    update_cache: yes
  become: true

- import_tasks: flatpak.yml

- import_tasks: heroic.yml

- import_tasks: retroarch.yml
