---
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - higan
  - libasound2-plugins:i386 # Workaround for Guild Wars 2 audio in CrossOver
  - steam
  become: true
