---
- name: Enable i386 architecture repositories (for Steam)
  command: dpkg --add-architecture i386
  become: true

- name: Accept Steam EULA
  debconf:
    name: steam
    question: steam/question
    vtype: select
    value: "I AGREE"
  become: true
 
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - higan
  - libasound2-plugins:i386 # Workaround for Guild Wars 2 audio in CrossOver
  - steam
  become: true
