homeautomation_common_volumes:
  - "{{ homeautomation_homeassistant_required_volumes.localtime }}:/etc/localtime:ro"
  - "{{ homeautomation_homeassistant_required_volumes.timezone }}:/etc/timezone:ro"

homeautomation_default_logging:
  driver: "json-file"
  options:
    max-size: "{{ homeautomation_docker_log_max_size }}"
    max-file: "{{ homeautomation_docker_log_max_file }}"

homeautomation_external_network:
  default:
    external: true
    name: "{{ homeautomation_docker_network_name }}"

homeautomation_tz: "{{ homeautomation_system_timezone.stdout.strip() }}"
