#!/bin/bash

set -e

[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }
[[ $# -eq 1 ]] || { echo "Usage: $(basename "${0}") luksName">&2; exit 1; }

name="${1}"
RETRY_SECS=3

# May not be mounted
mount_dirs="$(findmnt -rno TARGET "/dev/mapper/${name}")" || true
if [[ -n "${mount_dirs}" ]]; then
	echo "Unmounting: ${mount_dirs}"
	for mount_dir in "${mount_dirs}"; do
		if ! umount "${mount_dir}"; then
			echo "Sleeping for ${RETRY_SECS} seconds"
			sleep ${RETRY_SECS}
			umount "${mount_dir}"
		fi
	done
fi

echo "Closing LUKS device: ${name}"
cryptsetup luksClose "${name}"
