#!/bin/bash

set -e

[[ ${EUID} -eq 0 ]] || { echo 'Must be run as root'>&2; exit 1; }
[[ $# -eq 3 ]] || { echo "Usage: $(basename "${0}") luksName /dev/sda /key/file">&2; exit 1; }

name="${1}"
device="${2}"
key_file="${3}"

is_mapped() {
	cryptsetup status ${name} >/dev/null
}

open_luks() {
    cryptsetup --key-file "${key_file}" luksOpen ${device} ${name}
}

is_mapped || open_luks
