---
galaxy_info:
  author: andornaut
  description: Rsnapshot on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - rsnapshot
    - backup
    - ubuntu
