---
- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Configure rsnapshot
  ansible.builtin.import_tasks: rsnapshot.yml

- name: Configure backup schedules in cron
  ansible.builtin.import_tasks: cron.yml
