---
- name: Setup backup directory and scripts
  ansible.builtin.file:
    path: "{{ rsnapshot_directory }}"
    state: directory
    mode: "0700"
    owner: root
    group: root
  become: true

- name: Configure rsnapshot and scheduling
  ansible.builtin.template:
    src: rsnapshot.conf.j2
    dest: /etc/rsnapshot.conf
    mode: "0644"
  become: true
  notify: Validate rsnapshot configuration
