---
- name: Create the rsnapshot backup directory
  ansible.builtin.file:
    path: "{{ rsnapshot_directory }}"
    state: directory
    mode: "0700"
    owner: root
    group: root
  become: true

- name: Copy rsnapshot configuration file
  ansible.builtin.template:
    src: rsnapshot.conf.j2
    dest: /etc/rsnapshot.conf
    mode: "0644"
  become: true
  notify: Validate rsnapshot configuration
