---
- name: Resolve home directory for {{ hobbies_user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ hobbies_user }}"
  tags: always

- name: Import FPV tasks
  ansible.builtin.import_tasks: fpv.yml
  tags: fpv

- name: Import Kicad tasks
  ansible.builtin.import_tasks: kicad.yml
  tags: kicad

- name: Import OrcaSlicer tasks
  ansible.builtin.import_tasks: orcaslicer.yml
  tags: orcaslicer
