---
- name: Uninstall MTAs
  apt:
    name:
      - exim
      # Uninstall old version of msmtp
      - msmtp
      - postfix
      - sendmail
    state: absent
  become: true

- name: Install system packages
  apt:
    name:
      - s-nail
      # msmtp build dependencies
      - automake
      - gettext
      - libgnutls28-dev
      - libidn2-dev
      - libsecret-1-dev
      - libtool
      - mailutils
      - texinfo
    install_recommends: no
    state: latest
    update_cache: yes
  become: true

- name: Clone msmtp git repository
  git:
    #repo: https://git.marlam.de/git/msmtp.git
    repo: https://github.com/marlam/msmtp-mirror.git
    dest: /tmp/msmtp.git
    force: yes 

- name: Automake msmtp
  command:
    cmd: automake --add-missing
    chdir: /tmp/msmtp.git

- name: Autoreconf msmtp
  command: 
    cmd: autoreconf -i
    chdir: /tmp/msmtp.git

- name: Configure msmtp
  command:
    cmd: ./configure --sysconfdir=/etc
    chdir: /tmp/msmtp.git

# This fails when using gettext versions <0.20, which ships with Ubuntu hirsute
- name: Make msmtp
  make:
    chdir: /tmp/msmtp.git

- name: Make install msmtp
  make:
    chdir: /tmp/msmtp.git
    target: install
  become: true

- name: Copy msmtp config file
  template:
    src: msmtprc
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/aliases
  template:
    src: aliases
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/mailname
  template:
    src: mailname
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/mail.rc
  copy:
    src: mail.rc
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set msmtp as sendmail MTA in s-nail
  lineinfile:
    path: /etc/s-nail.rc
    regexp: '^set sendmail'
    line: 'set sendmail="/usr/local/bin/msmtp"'
  become: true

- name: Link sendmail to msmtp
  file:
    src: /usr/local/bin/msmtp
    dest: /usr/sbin/sendmail
    force: yes
    owner: root
    group: root
    state: link
  become: true
