---
- name: Uninstall MTAs
  apt:
    name: "{{ item }}"
    state: absent
  become: true
  with_items:
  - exim
  - postfix
  - sendmail

- name: Install system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: true
  with_items:
  - msmtp
  - s-nail

- name: Copy msmtp config file
  template:
    src: msmtprc
    dest: /etc/
    owner: root
    group: mail
    mode: 0644
  become: true

- name: Copy /etc/aliases
  template:
    src: aliases
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/mail.rc
  copy:
    src: mail.rc
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set msmtp as sendmail MTA in s-nail
  lineinfile:
    path: /etc/s-nail.rc
    regexp: '^set sendmail'
    line: 'set sendmail="/usr/bin/msmtp"'
  become: true

- name: Link sendmail to msmtp
  file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    owner: root
    group: root
    state: link
  become: true
