---
- name: Uninstall MTAs
  ansible.builtin.apt:
    name:
      - exim
      # Uninstall old version of msmtp
      - msmtp
      - postfix
      - sendmail
    state: absent
    install_recommends: false
    update_cache: true
  become: true

- name: Install system packages
  ansible.builtin.apt:
    name:
      - s-nail
      # msmtp build dependencies
      - autoconf
      - automake
      - autopoint
      # Requires gettext v0.21 from Ubuntu hirsute
      # https://github.com/marlam/msmtp-mirror/issues/55
      - gettext
      - gettext-base
      - libgnutls28-dev
      - libidn2-dev
      - libsecret-1-dev
      - libtool
      - mailutils
      - pkg-config
      - texinfo
    install_recommends: false
    state: present
    update_cache: true
  become: true

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: msmtp
  register: msmtp_build_dir

- name: Clone msmtp git repository
  ansible.builtin.git:
    repo: https://git.marlam.de/git/msmtp.git
    dest: "{{ msmtp_build_dir.path }}"
    depth: 1
    force: true
    version: master

- name: Autoreconf msmtp
  ansible.builtin.command:
    cmd: autoreconf -i --force
    chdir: "{{ msmtp_build_dir.path }}"
  changed_when: true

- name: Configure msmtp
  ansible.builtin.command:
    cmd: ./configure --sysconfdir=/etc
    chdir: "{{ msmtp_build_dir.path }}"
  changed_when: true

# This fails when using gettext versions <0.20,
# which ship with Ubuntu releases prior to hirsute
- name: Make msmtp
  community.general.make:
    chdir: "{{ msmtp_build_dir.path }}"

- name: Make install msmtp
  community.general.make:
    chdir: "{{ msmtp_build_dir.path }}"
    target: install
  become: true

- name: Copy msmtp config file
  ansible.builtin.template:
    src: msmtprc
    dest: /etc/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Copy /etc/aliases
  ansible.builtin.template:
    src: aliases
    dest: /etc/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Copy /etc/mailname
  ansible.builtin.template:
    src: mailname
    dest: /etc/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Copy /etc/mail.rc
  ansible.builtin.copy:
    src: mail.rc
    dest: /etc/
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Set msmtp as sendmail MTA in s-nail
  ansible.builtin.lineinfile:
    path: /etc/s-nail.rc
    regexp: '^set sendmail'
    line: 'set sendmail="/usr/local/bin/msmtp"'
  become: true

- name: Link sendmail to msmtp
  ansible.builtin.file:
    src: /usr/local/bin/msmtp
    dest: /usr/sbin/sendmail
    force: true
    owner: root
    group: root
    state: link
  become: true

- name: Cleanup build directory
  ansible.builtin.file:
    path: "{{ msmtp_build_dir.path }}"
    state: absent
