---
- name: Uninstall MTAs
  apt:
    name:
      - exim
      # Uninstall old version of msmtp
      - msmtp
      - postfix
      - sendmail
    state: absent
  become: true

- name: Install system packages
  apt:
    name:
      - s-nail
      # msmtp build dependencies
      - autoconf
      - automake
      - autopoint
      # Requires gettext v0.21 from Ubuntu hirsute
      # https://github.com/marlam/msmtp-mirror/issues/55
      - gettext
      - gettext-base
      - libgnutls28-dev
      - libidn2-dev
      - libsecret-1-dev
      - libtool
      - mailutils
      - pkg-config
      - texinfo
    install_recommends: no
    state: latest
    update_cache: yes
  become: true

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: msmtp
  register: build_dir

- name: Clone msmtp git repository
  git:
    repo: https://git.marlam.de/git/msmtp.git
    dest: "{{ build_dir.path }}"
    depth: 1
    force: yes

- name: Autoreconf msmtp
  command:
    cmd: autoreconf -i --force
    chdir: "{{ build_dir.path }}"

- name: Configure msmtp
  command:
    cmd: ./configure --sysconfdir=/etc
    chdir: "{{ build_dir.path }}"

# This fails when using gettext versions <0.20,
# which ship with Ubuntu releases prior to hirsute
- name: Make msmtp
  make:
    chdir: "{{ build_dir.path }}"

- name: Make install msmtp
  make:
    chdir: "{{ build_dir.path }}"
    target: install
  become: true

- name: Copy msmtp config file
  template:
    src: msmtprc
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/aliases
  template:
    src: aliases
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/mailname
  template:
    src: mailname
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy /etc/mail.rc
  copy:
    src: mail.rc
    dest: /etc/
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set msmtp as sendmail MTA in s-nail
  lineinfile:
    path: /etc/s-nail.rc
    regexp: "^set sendmail"
    line: 'set sendmail="/usr/local/bin/msmtp"'
  become: true

- name: Link sendmail to msmtp
  file:
    src: /usr/local/bin/msmtp
    dest: /usr/sbin/sendmail
    force: yes
    owner: root
    group: root
    state: link
  become: true

- name: Cleanup build directory
  file:
    path: "{{ build_dir.path }}"
    state: absent
