---
- name: Import pingtest tasks
  ansible.builtin.import_tasks: pingtest.yml
  tags: pingtest

- name: Import dns-healthcheck tasks
  ansible.builtin.import_tasks: dns-healthcheck.yml
  tags: dns-healthcheck
