---
- name: Configure Docker Repository
  become: true
  block:
    - name: Uninstall incompatible packages
      ansible.builtin.apt:
        name:
          # Old versions: https://docs.docker.com/engine/install/ubuntu/
          - containerd
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - docker.io
          - podman-docker
          - runc
        state: absent
        purge: true
        autoremove: true

    - name: Install Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={% if ansible_architecture == 'x86_64' %}amd64{% else %}{{ ansible_architecture }}{% endif %}
          signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: true

- name: Install Docker Packages
  become: true
  block:
    - name: Install docker-py Python package
      ansible.builtin.pip:
        name:
          - docker
        extra_args: "--break-system-packages"
        state: present

    - name: Install Docker system packages
      ansible.builtin.apt:
        name:
          - docker-registry
          - python3-docker
          # New versions: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
          - containerd.io
          - docker-buildx-plugin
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
        state: present
        install_recommends: false
        update_cache: true

- name: Configure Docker Services
  become: true
  block:
    - name: Start and enable Docker service
      ansible.builtin.systemd_service:
        name: docker
        daemon_reload: true
        state: started
        enabled: true

    - name: Start and enable Docker Registry service
      ansible.builtin.systemd_service:
        name: docker-registry
        daemon_reload: true
        state: started
        enabled: true

- name: Configure Docker maintenance cron job
  ansible.builtin.cron:
    name: "Docker system prune"
    cron_file: ansible-role-docker
    user: root
    special_time: weekly
    job: "docker system prune --all --force --filter 'until=168h' > /dev/null"
  become: true
