---
- name: Uninstall incompatible packages
  apt:
    name:
      # Old versions: https://docs.docker.com/engine/install/ubuntu/
      - containerd
      - docker-compose
      - docker-compose-v2
      - docker-doc
      - docker.io
      - podman-docker
      - runc
    state: absent
  become: true

- name: Install docker-py
  pip:
    name:
      - docker
    extra_args: "--break-system-packages"
  become: true

- name: Install Docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  become: true

- name: Add Docker ppa
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
    state: present
  become: true

- name: Install Docker system packages
  apt:
    name:
      - docker-registry
      - python3-docker
      # New versions: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
    state: latest
  become: true

- name: Start Docker on boot
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  become: true

- name: Start Docker Registry on boot
  systemd:
    name: docker-registry
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
