---
- name: Uninstall docker-py system package (workaround)
  apt:
    name: python3-docker
    state: absent
  become: true

# Workaround error: "Configuration error - kwargs_from_env() got an unexpected keyword argument 'ssl_version'"
# https://github.com/docker/docker-py/issues/3194
# https://github.com/geerlingguy/internet-pi/issues/567#issuecomment-1891163294
- name: Install docker-py==6.1.3 from PyPI (workaround)
  pip:
    name: 
      - "docker==6.1.3"
    extra_args: "--break-system-packages"
  become: true

- name: Install Docker system packages
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
  become: true

- name: Start Docker on boot
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  become: true

- name: Start Docker Registry on boot
  systemd:
    name: docker-registry
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
