---
- name: Install Kubernetes Tools
  block:
    - name: Get latest version of helm
      uri:
        url: https://api.github.com/repos/helm/helm/releases/latest
        return_content: true
      register: helm_version

    - name: Install helm binary
      unarchive:
        src: https://get.helm.sh/helm-{{ helm_version.json.tag_name }}-linux-amd64.tar.gz
        dest: /usr/local/bin/
        extra_opts:
          - "--strip-components=1"
        exclude:
          - LICENSE
          - README.md
        remote_src: true
        #creates: /usr/local/bin/helm

    - name: Get latest kubectl version
      uri:
        url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
        return_content: true
      register: kubectl_version

    - name: Install kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"
        #creates: /usr/local/bin/kubectl

    - name: Install minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: "0755"
        #creates: /usr/local/bin/minikube
  become: true
