---
# Use Avahi to make mDNS avaiable for Google Cast in Home Assistant without having to set --network_mode=host
# https://community.home-assistant.io/t/google-cast-with-docker-no-google-cast-devices-found/145331/24
- name: Install Avahi system packages
  ansible.builtin.apt:
    name:
      - avahi-daemon
    state: present
    install_recommends: false
    update_cache: true
  become: true
  when: (homeautomation_avahi_interfaces | length) > 0

- name: "Configure Avahi: allow-interfaces"
  community.general.ini_file:
    no_extra_spaces: true
    option: allow-interfaces
    path: /etc/avahi/avahi-daemon.conf
    section: server
    value: "{{ homeautomation_avahi_interfaces }}"
    mode: "0644"
  become: true
  notify: Restart Avahi service
  when: (homeautomation_avahi_interfaces | length) > 0

- name: "Configure Avahi: enable-reflector"
  community.general.ini_file:
    no_extra_spaces: true
    option: enable-reflector
    path: /etc/avahi/avahi-daemon.conf
    section: reflector
    value: "yes"
    mode: "0644"
  become: true
  notify: Restart Avahi service
  when: (homeautomation_avahi_interfaces | length) > 0
