---
- name: Remove ha-mcp container if it exists
  community.docker.docker_container:
    name: hamcp
    state: absent
  failed_when: false

- name: Start ha-mcp Docker container
  vars:
    hamcp_base_environment:
      HOMEASSISTANT_TOKEN: "{{ homeautomation_hamcp_token }}"
      HOMEASSISTANT_URL: "{{ homeautomation_hamcp_homeassistant_url }}"
      TZ: "{{ homeautomation_tz }}"
    hamcp_environment: >-
      {{ hamcp_base_environment | combine(homeautomation_hamcp_env | default({})) }}

  community.docker.docker_compose_v2:
    project_name: homeautomation-hamcp
    pull: always
    remove_orphans: true
    definition:
      networks: "{{ homeautomation_external_network }}"
      services:
        hamcp:
          # http://hamcp.internal:8086
          container_name: hamcp
          command: "fastmcp run fastmcp-http.json"
          environment: "{{ hamcp_environment }}"
          extra_hosts:
            - "host.docker.internal:host-gateway"
          image: "{{ homeautomation_hamcp_docker_image }}"
          logging: "{{ homeautomation_default_logging }}"
          # ports:
          #   - "8086:8086"
          restart: unless-stopped
          volumes: "{{ homeautomation_common_volumes }}"
  notify:
    - Restart homeassistant
    - Update /etc/hosts
