---
# Required vars:
#   container_names (list): containers to remove
- name: "Remove Docker containers: {{ container_names | join(', ') }}"
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ container_names }}"
  failed_when: false
