---
# Usage:
#   ansible.builtin.include_tasks: remove_docker_containers.yml
#   vars:
#     container_names:
#       - container1
#       - container2
- name: "Remove Docker containers: {{ container_names | join(', ') }}"
  community.docker.docker_container:
    name: "{{ item }}"
    state: absent
  loop: "{{ container_names }}"
  failed_when: false
