---
- name: Create www/ directory
  ansible.builtin.file:
    path: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Install advanced-camera-card
  block:
    - name: Download advanced-camera-card
      ansible.builtin.get_url:
        url: https://github.com/dermotduffy/advanced-camera-card/releases/latest/download/advanced-camera-card.zip
        dest: /tmp/advanced-camera-card.zip
        mode: "0644"

    - name: Create advanced-camera-card directory
      ansible.builtin.file:
        path: "{{ homeautomation_homeassistant_required_volumes.config }}/www/advanced-camera-card"
        state: directory
        mode: "0755"
      become: true

    - name: Install advanced-camera-card files
      ansible.builtin.unarchive:
        src: /tmp/advanced-camera-card.zip
        dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/advanced-camera-card"
        remote_src: true
        # Drop the ./dist directory
        # -j junk  paths. The  archive's directory structure is not recreated;
        # all files are deposited in the extraction directory (by default, the current one).
        extra_opts: "-j"
      become: true

- name: Install Button Card
  ansible.builtin.get_url:
    url: https://github.com/custom-cards/button-card/releases/latest/download/button-card.js
    dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"
    mode: "0644"
  become: true

- name: Install Card Mod
  ansible.builtin.include_tasks: install_github_release_component.yml
  vars:
    github_component_name: Card Mod
    github_component_repo: thomasloven/lovelace-card-mod
    github_component_src: card-mod.js
    github_component_dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"

- name: Install Custom Features Tile Card
  ansible.builtin.include_tasks: install_github_release_component.yml
  vars:
    github_component_name: Custom Features Tile Card
    github_component_repo: Nerwyn/custom-card-features
    github_component_src: dist/custom-card-features.min.js
    github_component_dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"

- name: Install Decluttering Card
  ansible.builtin.get_url:
    url: https://github.com/custom-cards/decluttering-card/releases/latest/download/decluttering-card.js
    dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"
    mode: "0644"
  become: true

- name: Install Slider Entry Row Card
  ansible.builtin.include_tasks: install_github_release_component.yml
  vars:
    github_component_name: Slider Entry Row Card
    github_component_repo: thomasloven/lovelace-slider-entity-row
    github_component_src: slider-entity-row.js
    github_component_dest: "{{ homeautomation_homeassistant_required_volumes.config }}/www/"
