---
- name: Update crypttab for nas_raid_devices
  lineinfile:
    path: /etc/crypttab
    line: "nas{{ index }} {{ item }} {{ nas_key_file }} luks,noauto"
    regexp: "^nas{{ index }}"
  loop: "{{ nas_raid_devices }}"
  loop_control:
    index_var: index
  become: true

- name: Update crypttab for nas_backup_device
  lineinfile:
    path: /etc/crypttab
    line: "nasbackup {{ nas_backup_device }} {{ nas_key_file }} luks,noauto"
    regexp: "^nasbackup"
  when: nas_backup_device is defined
  become: true

- name: Update fstab
  lineinfile:
    path: /etc/fstab
    line: "/dev/mapper/nas0 /media/nas btrfs noauto,{% for i in range(nas_raid_devices|length) %}device=/dev/mapper/nas{{ i }}{% if i == 0 %},{% endif %}{% endfor %} 0 0"
    regexp: "^\/dev\/mapper\/nas0"
  become: true

- name: Install backupnas
  template:
    src: backupnas
    dest: /usr/local/bin/
    mode: 0755
  when: nas_backup_device is defined
  become: true

- name: Override media-nas.mount Systemd unit
  template:
    src: override.conf
    dest: /etc/systemd/system/media-nas.mount.d/
  become: true


- name: Secure key_file owernship
  file:
    path: "{{ nas_key_file }}"
    owner: root
    group: root
    mode: '0400'
  become: true
