---
- name: Install templated scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - backupnas
    - mountnas
  become: true

- name: Install scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - closeluks
    - openluks
  become: true
  delegate_to: localhost


- name: Copy mountnas systemd unit file
  template:
    src: mountnas.service
    dest: /etc/systemd/system/
  become: true
  notify: restart mountnas

- name: Start mountnas service on boot
  systemd:
    name: mountnas
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
