---
- name: Check if usb_modeswitch.conf exists
  stat:
    path: /etc/usb_modeswitch.conf
  register: stat_usb_modeswitch.conf

# See:
# https://bugs.launchpad.net/ubuntu/+source/usb-modeswitch/+bug/755342
# https://ubuntuforums.org/archive/index.php/t-1551985.html
- name: Workaround usb modeswitching bug
  lineinfile:
    path: /etc/usb_modeswitch.conf
    line: "DisableSwitching=1"
    regex: "^#?\\s*DisableSwitching\\s*"
  become: true
  when: stat_usb_modeswitch.conf.stat.exists


# Workaround error in boot log:
# libbd_mdraid.so.2: cannot open shared object file
# https://bugs.launchpad.net/ubuntu/+source/udisks2/+bug/1811724
- name: Install system dependencies
  apt:
    name: libblockdev-mdraid2
    state: latest
    update_cache: yes
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  loop:
    - "{{ nas_backup_mount_directory }}"
    - "{{ nas_raid_mount_directory }}"
  become: true

- name: Update crypttab for nas_raid_devices
  lineinfile:
    path: /etc/crypttab
    line: "nas{{ index }} {{ item }} {{ nas_key_file }} luks,noauto"
    regexp: "^nas{{ index }}"
  loop: "{{ nas_raid_devices }}"
  loop_control:
    index_var: index
  become: true
  notify: Reload systemd

- name: Update fstab for nas_raid_devices
  lineinfile:
    path: /etc/fstab
    line: "/dev/mapper/nas0 {{ nas_raid_mount_directory }} {{ nas_raid_fs_type }} {{ nas_raid_fs_defaults }},{% for i in range(nas_raid_devices|length) %}device=/dev/mapper/nas{{ i }},x-systemd.after=blockdev@dev-mapper-nas{{ i }}.target,x-systemd.requires=dev-mapper-nas{{ i }}.device,x-systemd.requires-mounts-for=/dev/mapper/nas{{ i }}{% if i == 0 %},{% endif %}{% endfor %}{% if nas_raid_wanted_by is defined %},x-systemd.after={{ nas_raid_wanted_by }},x-systemd.wanted-by={{ nas_raid_wanted_by }}{% endif %},x-systemd.device-timeout=10s 0 0"
    regexp: "^\/dev\/mapper\/nas0"
  become: true
  notify: Reload systemd

- name: Update crypttab for nas_backup_device
  lineinfile:
    path: /etc/crypttab
    line: "nasbackup {{ nas_backup_device }} {{ nas_key_file }} luks,noauto"
    regexp: "^nasbackup"
  become: true
  notify: Reload systemd
  when: nas_backup_device is defined

- name: Update fstab for nas_backup_device
  lineinfile:
    path: /etc/fstab
    line: "/dev/mapper/nasbackup {{ nas_backup_mount_directory }} {{ nas_backup_fs_type }} {{ nas_backup_fs_defaults }} 0 0"
    regexp: "^\/dev\/mapper\/nasbackup"
  become: true
  notify: Reload systemd
  when: nas_backup_device is defined

- name: Install backupnas script
  template:
    src: backupnas
    dest: /usr/local/bin/
    mode: 0755
  become: true
  when: nas_backup_device is defined

- name: Secure key_file owernship
  file:
    path: "{{ nas_key_file }}"
    owner: root
    group: root
    mode: '0400'
