---
- name: System dependencies
  block:
    - name: Install system dependencies
      apt:
        name:
          - btrfsmaintenance
          - libblockdev-mdraid2
        state: latest
        install_recommends: false
        update_cache: true
      become: true

- name: USB configuration
  block:
    - name: Check if usb_modeswitch.conf exists
      stat:
        path: /etc/usb_modeswitch.conf
      register: stat_usb_modeswitch

    - name: Workaround usb modeswitching bug
      lineinfile:
        path: /etc/usb_modeswitch.conf
        line: "DisableSwitching=1"
        regex: "^#?\\s*DisableSwitching\\s*"
      when: stat_usb_modeswitch.stat.exists
      become: true
  # TODO: This is disabled, b/c the workaround may no longer be necessary
  # See:
  # https://bugs.launchpad.net/ubuntu/+source/usb-modeswitch/+bug/755342
  # https://ubuntuforums.org/archive/index.php/t-1551985.html
  when: false

- name: Storage setup
  block:
    - name: Create directories
      file:
        path: "{{ item }}"
        owner: root
        group: root
        state: directory
      loop:
        - "{{ nas_raid_mount_directory }}"
        - "{% if nas_backup_device is defined %}{{ nas_backup_mount_directory }}{% endif %}"
      when: item != ""

    - name: Update crypttab for nas_raid_devices
      lineinfile:
        path: /etc/crypttab
        line: "nas{{ index }} {{ item }} {{ nas_key_file }} luks,noauto"
        regexp: "^nas{{ index }}"
      loop: "{{ nas_raid_devices }}"
      loop_control:
        index_var: index
      notify: Reload systemd

    - name: Update fstab for nas_raid_devices
      lineinfile:
        path: /etc/fstab
        line: "/dev/mapper/nas0 {{ nas_raid_mount_directory }} {{ nas_raid_fs_type }} {{ nas_raid_fs_defaults }},{% for i in range(nas_raid_devices|length) %}{% if nas_raid_fs_type == 'btrfs' %}device=/dev/mapper/nas{{ i }},{% endif %}x-systemd.after=blockdev@dev-mapper-nas{{ i }}.target,x-systemd.requires=dev-mapper-nas{{ i }}.device,x-systemd.requires-mounts-for=/dev/mapper/nas{{ i }}{% if i < (nas_raid_devices|length -1) %},{% endif %}{% endfor %},x-systemd.device-timeout=20s 0 0"
        regexp: "^\/dev\/mapper\/nas0"
      notify: Reload systemd
  become: true

- name: Backup configuration
  block:
    - name: Update crypttab for nas_backup_device
      lineinfile:
        path: /etc/crypttab
        line: "nasbackup {{ nas_backup_device }} {{ nas_key_file }} luks,noauto"
        regexp: "^nasbackup"
      notify: Reload systemd

    - name: Update fstab for nas_backup_device
      lineinfile:
        path: /etc/fstab
        line: "/dev/mapper/nasbackup {{ nas_backup_mount_directory }} {{ nas_backup_fs_type }} {{ nas_backup_fs_defaults }} 0 0"
        regexp: "^\/dev\/mapper\/nasbackup"
      notify: Reload systemd

    - name: Install backupnas script
      template:
        src: backupnas
        dest: /usr/local/bin/
        mode: 0755
  become: true
  when: nas_backup_device is defined

- name: Security and systemd configuration
  block:
    - name: Secure key_file ownership
      file:
        path: "{{ nas_key_file }}"
        owner: root
        group: root
        mode: "0400"

    - name: Install nas-luks-key.path
      template:
        src: nas-luks-key.path
        dest: /etc/systemd/system/
      notify: Reload systemd

    - name: Enable nas-luks-key.path
      ansible.builtin.systemd:
        name: nas-luks-key.path
        enabled: true
        masked: false
        state: started
      notify: Reload systemd
  become: true
