---
- name: Install system packages
  ansible.builtin.apt:
    name:
      - gh
      - git
      - git-delta
      - jq
      - libmysqlclient-dev
      - libxml2-dev
      - libxslt-dev
      - meld
      - mercurial
      - mysql-client
      - postgresql-client
      - shellcheck
      - wireshark
      - xserver-xephyr
    state: latest
    install_recommends: false
    update_cache: true
  become: true
