---
- name: Get latest Go version
  ansible.builtin.uri:
    url: https://go.dev/dl/?mode=json
    return_content: true
  register: dev_go_releases

- name: Set Go version fact
  ansible.builtin.set_fact:
    dev_go_version: "{{ dev_go_releases.json[0].version }}"

- name: Download Go tarball
  ansible.builtin.get_url:
    url: "https://go.dev/dl/{{ dev_go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/{{ dev_go_version }}.linux-amd64.tar.gz"
    mode: "0644"

- name: Remove Go packages from apt
  ansible.builtin.apt:
    name:
      - golang
      - golang-go
      - golang-doc
      - gccgo-go
    state: absent
    purge: true
    autoremove: true
  become: true

- name: Remove old Go installation
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true

- name: Extract Go tarball to /usr/local
  ansible.builtin.unarchive:
    src: "/tmp/{{ dev_go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  become: true
