- name: Install deadsnakes apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 6A755776
  become: true

- name: Install Python 3.7 apt respository
  apt_repository:
    repo: deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu {{ ansible_distribution_release }} main
    update_cache: yes
  become: true

- name: Install Python 3.7
  apt:
    name: python3.7
    state: latest
    update_cache: yes
  become: true
