---
- name: Install Python system packages
  apt:
    name:
      # Avoid error: fatal error: ffi.h: No such file or directory
      - libffi-dev
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-virtualenvwrapper
      - virtualenvwrapper
    state: latest
    update_cache: yes
  become: true

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: true

- name: Install/upgrade Pipenv
  pip:
    name: pipenv
    state: latest
  become: true
