---
- name: Install Python system packages
  apt:
    name:
      - python3-dev
      - python3-pip
      - python3-virtualenvwrapper
      - virtualenvwrapper
    state: latest
    update_cache: yes
  become: true

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: true
