---
- name: Install Python system packages
  apt:
    name:
      # Avoid error: fatal error: ffi.h: No such file or directory
      - libffi-dev
      - python3-dev
      - python3-pip
      - python3-venv
    state: latest
    update_cache: yes
  become: true

- name: Link python to python3
  community.general.alternatives:
    name: python
    path: /usr/bin/python3
    link: /usr/bin/python
    priority: 0
  become: true

- name: Install the latest pip
  pip:
    name: pip
    state: latest
  become: true

- name: Install the latest Pipenv
  pip:
    name: pipenv
    state: latest
  become: true
