---
- name: Install QEMU
  ansible.builtin.apt:
    name:
      - ovmf
      - qemu-system-x86
      - qemu-utils
      - swtpm
    install_recommends: false
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true

- name: Add the user to kvm, which hardware acceleration requires
  ansible.builtin.user:
    name: "{{ dev_user }}"
    groups: kvm
    append: true
  become: true
