---
- name: Install Ruby system packages
  ansible.builtin.apt:
    name:
      - ruby
      - ruby-dev
    state: present
    install_recommends: false
    update_cache: true
  become: true

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: dev_tmp_ruby

- name: Install Ruby tools
  block:
    - name: Install chruby
      block:
        - name: Get releases of chruby
          ansible.builtin.uri:
            url: https://api.github.com/repos/postmodern/chruby/releases
            return_content: true
          register: dev_chruby_releases

        - name: Set chruby to latest stable release
          ansible.builtin.set_fact:
            dev_chruby_release: "{{ dev_chruby_releases.json | selectattr('prerelease', 'equalto', false) | selectattr('draft', 'equalto', false) | first }}"

        - name: Set chruby download URL fact
          ansible.builtin.set_fact:
            dev_chruby_download_url: "{{ dev_chruby_release.assets | selectattr('name', 'match', 'chruby-.*.tar.gz') | map(attribute='browser_download_url') | first }}"

        - name: Download chruby package
          ansible.builtin.get_url:
            url: "{{ dev_chruby_download_url }}"
            dest: "{{ dev_tmp_ruby.path }}/chruby.tar.gz"
            mode: "0644"

        - name: Decompress chruby.tar.gz
          ansible.builtin.unarchive:
            src: "{{ dev_tmp_ruby.path }}/chruby.tar.gz"
            remote_src: true
            dest: "{{ dev_tmp_ruby.path }}"

        - name: Make install chruby
          community.general.make:
            chdir: >-
              {{ dev_tmp_ruby.path }}/chruby-{{ dev_chruby_release.tag_name | replace('v', '') }}
            target: install
          become: true

    - name: Install ruby-install
      block:
        - name: Get releases of ruby-install
          ansible.builtin.uri:
            url: https://api.github.com/repos/postmodern/ruby-install/releases
            return_content: true
          register: dev_ruby_install_releases

        - name: Set ruby-install to latest stable release
          ansible.builtin.set_fact:
            dev_ruby_install_release: "{{ dev_ruby_install_releases.json | selectattr('prerelease', 'equalto', false) | selectattr('draft', 'equalto', false) | first }}"

        - name: Set ruby-install download URL fact
          ansible.builtin.set_fact:
            dev_ruby_install_download_url: "{{ dev_ruby_install_release.assets | selectattr('name', 'match', 'ruby-install-.*.tar.gz') | map(attribute='browser_download_url') | first }}"

        - name: Download ruby-install package
          ansible.builtin.get_url:
            url: "{{ dev_ruby_install_download_url }}"
            dest: "{{ dev_tmp_ruby.path }}/ruby-install.tar.gz"
            mode: "0644"

        - name: Decompress ruby-install.tar.gz
          ansible.builtin.unarchive:
            src: "{{ dev_tmp_ruby.path }}/ruby-install.tar.gz"
            remote_src: true
            dest: "{{ dev_tmp_ruby.path }}"

        - name: Make install ruby-install
          community.general.make:
            chdir: >-
              {{ dev_tmp_ruby.path }}/ruby-install-{{ dev_ruby_install_release.tag_name | replace('v', '') }}
            target: install
          become: true
