---
- name: Install Ruby system packages
  apt:
    name:
      - ruby
      - ruby-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Create a temporary directory
  tempfile:
    state: directory
  register: tmp_ruby

- name: Install Ruby tools
  block:
    - name: Install chruby
      block:
        - name: Get the latest version of chruby
          uri:
            url: https://api.github.com/repos/postmodern/chruby/releases/latest
            return_content: true
          register: chruby_version

        - name: Download chruby package
          get_url:
            url: "{{ chruby_version.json.assets[0].browser_download_url }}"
            dest: "{{ tmp_ruby.path }}/chruby.tar.gz"
            mode: 0644

        - name: Decompress chruby.tar.gz
          ansible.builtin.unarchive:
            src: "{{ tmp_ruby.path }}/chruby.tar.gz"
            remote_src: true
            dest: "{{ tmp_ruby.path}}"

        - name: Make install chruby
          make:
            chdir: "{{ tmp_ruby.path}}/chruby-{{ chruby_version.json.name }}"
            target: install
          become: true

    - name: Install ruby-install
      block:
        - name: Get the latest version of ruby-install
          uri:
            url: https://api.github.com/repos/postmodern/ruby-install/releases/latest
            return_content: true
          register: ruby_install_version

        - name: Download ruby-install package
          get_url:
            url: "{{ ruby_install_version.json.assets[0].browser_download_url }}"
            dest: "{{ tmp_ruby.path }}/ruby-install.tar.gz"
            mode: 0644

        - name: Decompress ruby-install.tar.gz
          ansible.builtin.unarchive:
            src: "{{ tmp_ruby.path }}/ruby-install.tar.gz"
            remote_src: true
            dest: "{{ tmp_ruby.path }}"

        - name: Make install ruby-install
          make:
            chdir: "{{ tmp_ruby.path }}/ruby-install-{{ ruby_install_version.json.name }}"
            target: install
          become: true
