---
- name: Install Ruby system packages
  ansible.builtin.apt:
    name:
      - ruby
      - ruby-dev
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: dev_tmp_ruby

- name: Install Ruby tools
  block:
    - name: Download and install chruby
      block:
        - name: Get chruby releases
          ansible.builtin.uri:
            url: https://api.github.com/repos/postmodern/chruby/releases
            return_content: true
          register: dev_chruby_releases

        - name: Set chruby release fact
          ansible.builtin.set_fact:
            dev_chruby_release: "{{ dev_chruby_releases.json | selectattr('prerelease', 'equalto', false) | selectattr('draft', 'equalto', false) | first }}"

        - name: Set chruby download URL fact
          ansible.builtin.set_fact:
            dev_chruby_download_url: >-
              {{ dev_chruby_release.assets
              | selectattr('name', 'match', 'chruby-.*.tar.gz')
              | map(attribute='browser_download_url') | first }}

        - name: Download chruby package
          ansible.builtin.get_url:
            url: "{{ dev_chruby_download_url }}"
            dest: "{{ dev_tmp_ruby.path }}/chruby.tar.gz"
            mode: "0644"

        - name: Extract chruby archive
          ansible.builtin.unarchive:
            src: "{{ dev_tmp_ruby.path }}/chruby.tar.gz"
            remote_src: true
            dest: "{{ dev_tmp_ruby.path }}"

        - name: Install chruby
          community.general.make:
            chdir: >-
              {{ dev_tmp_ruby.path }}/chruby-{{ dev_chruby_release.tag_name | replace('v', '') }}
            target: install
          become: true

    - name: Download and install ruby-install
      block:
        - name: Get ruby-install releases
          ansible.builtin.uri:
            url: https://api.github.com/repos/postmodern/ruby-install/releases
            return_content: true
          register: dev_ruby_install_releases

        - name: Set ruby-install release fact
          ansible.builtin.set_fact:
            dev_ruby_install_release: "{{ dev_ruby_install_releases.json | selectattr('prerelease', 'equalto', false) | selectattr('draft', 'equalto', false) | first }}" # noqa: yaml[line-length]

        - name: Set ruby-install download URL fact
          ansible.builtin.set_fact:
            dev_ruby_install_download_url: >-
              {{ dev_ruby_install_release.assets
              | selectattr('name', 'match', 'ruby-install-.*.tar.gz')
              | map(attribute='browser_download_url') | first }}

        - name: Download ruby-install package
          ansible.builtin.get_url:
            url: "{{ dev_ruby_install_download_url }}"
            dest: "{{ dev_tmp_ruby.path }}/ruby-install.tar.gz"
            mode: "0644"

        - name: Extract ruby-install archive
          ansible.builtin.unarchive:
            src: "{{ dev_tmp_ruby.path }}/ruby-install.tar.gz"
            remote_src: true
            dest: "{{ dev_tmp_ruby.path }}"

        - name: Install ruby-install
          community.general.make:
            chdir: >-
              {{ dev_tmp_ruby.path }}/ruby-install-{{ dev_ruby_install_release.tag_name | replace('v', '') }}
            target: install
          become: true
  always:
    - name: Remove the temporary directory
      ansible.builtin.file:
        path: "{{ dev_tmp_ruby.path }}"
        state: absent
      when: dev_tmp_ruby.path is defined
      become: true
