---
- name: Install Rust system packages
  apt:
    name:
      - rustup
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Install Rust toolchain
  command: rustup default stable
  become: false
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
