---
- name: Install Rust system packages
  ansible.builtin.apt:
    name:
      - rustup
    state: latest
    install_recommends: false
    update_cache: true
  become: true

- name: Install Rust toolchain
  ansible.builtin.command: rustup default stable
  become: false
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustc"
