---
- name: Install Virtualbox system packages
  apt:
    name:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
    update_cache: yes
  become: true

- name: Disable vboxweb (workaround failure to start)
  systemd:
    name: vboxweb
    daemon_reload: yes
    state: stopped
    enabled: no
  ignore_errors: yes
  become: true
