---
- name: Accept virtualbox-ext-pack license
  ansible.builtin.debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select
  become: true

- name: Accept virtualbox-ext-pack license seen
  ansible.builtin.debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: seen
  become: true

- name: Install Virtualbox packages
  ansible.builtin.apt:
    name:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
    install_recommends: false
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true

- name: Blacklist KVM modules to prevent conflict with VirtualBox
  ansible.builtin.copy:
    dest: /etc/modprobe.d/blacklist-kvm.conf
    content: |
      blacklist kvm_amd
      blacklist kvm
    mode: "0644"
  become: true
  notify: Update initramfs

# If seeing an error: "Kernel driver not installed (rc=-1908)" or "VirtualBox kernel modules not loaded"
# Run: `sudo apt install --reinstall virtualbox-dkms virtualbox`
