---
# TODO: These license questions have changed, and need to be updated
# https://www.reddit.com/r/ansible/comments/l1wof8/install_virtualboxextpack_accepting_the_eula/
- name: Accept virtualbox-ext-pack seen license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: seen
  become: true

- name: Accept virtualbox-ext-pack select license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select
  become: true

- name: Install Virtualbox system packages
  apt:
    name:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
    install_recommends: false
    update_cache: true
  become: true
