---
- name: Accept virtualbox-ext-pack license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select
  become: true

- name: Accept virtualbox-ext-pack license seen
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: seen
  become: true

- name: Install Virtualbox packages
  apt:
    name:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
    install_recommends: false
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true

# If seeing an error: "Kernel driver not installed (rc=-1908)" or "VirtualBox kernel modules not loaded"
# Run: `sudo apt install --reinstall virtualbox-dkms virtualbox`
