---
# https://www.reddit.com/r/ansible/comments/l1wof8/install_virtualboxextpack_accepting_the_eula/
- name: Accept virtualbox-ext-pack seen license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: seen
  become: true

- name: Accept virtualbox-ext-pack select license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select
  become: true

- name: Install Virtualbox system packages
  apt:
    name:
      - virtualbox
      - virtualbox-dkms
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
    state: latest
    update_cache: yes
  become: true

- name: Disable vboxweb (workaround failure to start)
  systemd:
    name: vboxweb
    daemon_reload: yes
    state: stopped
    enabled: no
  ignore_errors: true
  become: true
