---
- name: Add Microsoft apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: Add Visual Studio Code apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: true

- name: Install Visual Studio Code
  apt:
    name: visual-studio-code
    state: latest
    update_cache: yes
  become: true
