---
- name: Start Home Assistant Docker container
  vars:
    required_volumes:
      - "{{ homeassistant_docker_volumes.config }}:/config"
      - "{{ homeassistant_docker_volumes.localtime }}:/etc/localtime:ro"
  docker_compose:
    project_name: homeassistant
    pull: yes
    recreate: always
    definition:
      version: "3"
      services:
        homeassistant:
          container_name: homeassistant
          image: "{{ homeassistant_docker_image }}"
          network_mode: host
          restart: unless-stopped
          volumes:
            "{{ required_volumes + homeassistant_docker_volumes_extra }}"
