---
# Use Avahi to make mDNS avaiable for Google Cast in Home Assistant without having to set --network_mode=host
# https://community.home-assistant.io/t/google-cast-with-docker-no-google-cast-devices-found/145331/24
- name: Install system packages
  apt:
    name:
      - avahi-daemon
    state: latest
    update_cache: yes
  become: true
  when: homeassistantfrigate_avahi_interfaces | length > 0

- name: "Configure Avahi: allow-interfaces"
  community.general.ini_file:
    no_extra_spaces: true
    option: allow-interfaces
    path: /etc/avahi/avahi-daemon.conf
    section: server
    value: "{{ homeassistantfrigate_avahi_interfaces }}"
  become: true
  register: avahi_allow_interfaces
  when: homeassistantfrigate_avahi_interfaces | length > 0

- name: "Configure Avahi: enable-reflector"
  community.general.ini_file:
    no_extra_spaces: true
    option: enable-reflector
    path: /etc/avahi/avahi-daemon.conf
    section: reflector
    value: "yes"
  become: true
  register: avahi_enable_reflector
  when: homeassistantfrigate_avahi_interfaces | length > 0

- name: Restart Avahi service
  systemd:
    name: avahi-daemon
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  when: avahi_allow_interfaces.changed or avahi_enable_reflector.changed
