---
- name: Install Bluetooth system packages
  apt:
    name:
      - bluez
      - dbus-broker
    state: latest
  become: true

- name: Enable and start dbus-broker service
  ansible.builtin.systemd_service:
    name: dbus-broker
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Copy docker-ble-policy
  ansible.builtin.copy:
    src: homeassistant/docker-ble-policy
    dest: /etc/apparmor.d/
    owner: root
    group: root
    mode: "0644"
  register: apparmor_policy
  become: true

- name: Load docker-ble-policy
  ansible.builtin.shell: apparmor_parser -r -W /etc/apparmor.d/docker-ble-policy
  become: true
  when: apparmor_policy.changed
# Shouldn't need to reload if we're loading the new profile above
#- name: Reload apparmor.service
#  ansible.builtin.systemd_service:
#    name: apparmor.service
#    state: restarted
#  when: apparmor_policy.changed
#  become: true
