---
- name: Start "Voice" Docker containers
  vars:
    microwakeword_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      # No data directory

    openwakeword_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_openwakeword_required_volumes.data }}:/custom"

    piper_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_piper_required_volumes.data }}:/data"

    whisper_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_whisper_required_volumes.data }}:/data"

  community.docker.docker_compose_v2:
    project_name: homeassistant-frigate-voice
    pull: always
    remove_orphans: true
    definition:
      networks:
        default:
          external: true
          name: homeassistant-frigate_default

      services:
        # Voice Preview (hardware) uses microWakeWord, not openWakeWord
        #openwakeword:
        #  http://openwakeword:11434
        #  container_name: openwakeword
        #  image: "{{ homeassistantfrigate_openwakeword_docker_image }}"
        #  command: --custom-model-dir /custom --preload-model 'ok_nabu'
        #  restart: unless-stopped
        #  volumes: "{{ openwakeword_volumes }}"

        # Used by Voice Preview (hardware)
        #microwakeword:
        #  http://microwakeword:11434
        #  container_name: microwakeword
        #  image: "{{ homeassistantfrigate_microwakeword_docker_image }}"
        #  restart: unless-stopped
        #  volumes: "{{ microwakeword_volumes }}"

        piper:
          # http://piper:10200
          container_name: piper
          image: rhasspy/wyoming-piper
          command: "{{ homeassistantfrigate_piper_command }}"
          restart: unless-stopped
          volumes: "{{ piper_volumes }}"

        whisper:
          # http://whisper:10300
          container_name: whisper
          image: rhasspy/wyoming-whisper
          command: "{{ homeassistantfrigate_whisper_command }}"
          restart: unless-stopped
          volumes: "{{ whisper_volumes }}"
