---
- name: Get group ids
  getent:
    database: group

- name: Copy docker-ble-policy
  ansible.builtin.copy:
    src: homeassistant/docker-ble-policy
    dest: /etc/apparmor.d/
    owner: root
    group: root
    mode: "0644"
  register: apparmor_policy
  become: true

- name: Load docker-ble-policy
  ansible.builtin.shell: apparmor_parser -r -W /etc/apparmor.d/docker-ble-policy
  become: true
  when: apparmor_policy.changed

# Shouldn't need to reload if we're loading the new profile above
#- name: Reload apparmor.service
#  ansible.builtin.systemd_service:
#    name: apparmor.service
#    state: restarted
#  when: apparmor_policy.changed
#  become: true

# Use Avahi to make mDNS avaiable for Google Cast in Home Assistant without having to set --network_mode=host
# https://community.home-assistant.io/t/google-cast-with-docker-no-google-cast-devices-found/145331/24
- name: Install system packages
  apt:
    name:
      - avahi-daemon
    state: latest
    update_cache: yes
  become: true
  when: homeassistantfrigate_avahi_interfaces | length > 0

- name: Configure allow-interfaces
  ansible.builtin.lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^allow-interfaces\\s*="
    line: "allow-interfaces={{ homeassistantfrigate_avahi_interfaces }}"
  become: true
  when: homeassistantfrigate_avahi_interfaces | length > 0
  register: avahi_allow_interfaces

- name: Configure enable-reflector
  ansible.builtin.lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^enable-reflector\\s*="
    line: "enable-reflector=yes"
  become: true
  when: homeassistantfrigate_avahi_interfaces | length > 0
  register: avahi_enable_reflector

- name: Restart Avahi service
  systemd:
    name: avahi-daemon
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  when: avahi_allow_interfaces.changed or avahi_enable_reflector.changed
