---
- name: Start ESPHome Docker container
  vars:
    esphome_base_volumes:
      - "{{ homeassistantfrigate_esphome_required_volumes.config }}:/config"
    esphome_volumes: "{{ common_volumes + esphome_base_volumes }}"

  community.docker.docker_compose_v2:
    project_name: homeassistant-frigate-esphome
    pull: always
    remove_orphans: true
    definition:
      networks: "{{ external_network }}"
      services:
        esphome:
          container_name: esphome
          environment:
            - ESPHOME_DASHBOARD_USE_PING=true
          image: "{{ homeassistantfrigate_esphome_docker_image }}"
          logging: "{{ default_logging }}"
          ports:
            - "{{ homeassistantfrigate_esphome_port }}:6052"
          restart: unless-stopped
          volumes: "{{ esphome_volumes }}"
