---
- name: Start Voice Docker containers
  vars:
    #microwakeword_volumes: "{{ common_volumes }}"
    #
    #openwakeword_service_volumes:
    #  - "{{ homeassistantfrigate_openwakeword_required_volumes.data }}:/custom"
    #openwakeword_volumes: "{{ common_volumes + openwakeword_service_volumes }}"

    piper_service_volumes:
      - "{{ homeassistantfrigate_piper_required_volumes.data }}:/data"
    piper_volumes: "{{ common_volumes + piper_service_volumes }}"

    whisper_service_volumes:
      - "{{ homeassistantfrigate_whisper_required_volumes.data }}:/data"
    whisper_volumes: "{{ common_volumes + whisper_service_volumes }}"

  community.docker.docker_compose_v2:
    project_name: homeassistant-frigate-voice
    pull: always
    remove_orphans: true
    definition:
      networks: "{{ external_network }}"
      services:
        # Voice Preview (hardware) uses microWakeWord, not openWakeWord
        #openwakeword:
        #  http://openwakeword:11434
        #  container_name: openwakeword
        #  image: "{{ homeassistantfrigate_openwakeword_docker_image }}"
        #  command: --custom-model-dir /custom --preload-model 'ok_nabu'
        #  logging: "{{ default_logging }}"
        #  restart: unless-stopped
        #  volumes: "{{ openwakeword_volumes }}"

        # Used by Voice Preview (hardware)
        #microwakeword:
        #  http://microwakeword:11434
        #  container_name: microwakeword
        #  image: "{{ homeassistantfrigate_microwakeword_docker_image }}"
        #  logging: "{{ default_logging }}"
        #  restart: unless-stopped
        #  volumes: "{{ microwakeword_volumes }}"

        piper:
          # http://piper:10200
          container_name: piper
          image: "{{ homeassistantfrigate_piper_docker_image }}"
          command: "{{ homeassistantfrigate_piper_command }}"
          restart: unless-stopped
          logging: "{{ default_logging }}"
          volumes: "{{ piper_volumes }}"

        whisper:
          # http://whisper:10300
          container_name: whisper
          image: "{{ homeassistantfrigate_whisper_docker_image }}"
          command: "{{ homeassistantfrigate_whisper_command }}"
          restart: unless-stopped
          logging: "{{ default_logging }}"
          volumes: "{{ whisper_volumes }}"
