---
- name: Remove ESPHome container if it exists
  community.docker.docker_container:
    name: esphome
    state: absent
  ignore_errors: true

- name: Start ESPHome Docker container
  vars:
    esphome_base_volumes:
      - "{{ homeassistantfrigate_esphome_required_volumes.config }}:/config"
    esphome_volumes: "{{ common_volumes + esphome_base_volumes }}"

  community.docker.docker_compose_v2:
    project_name: homeassistantfrigate-esphome
    pull: always
    remove_orphans: true
    definition:
      networks: "{{ external_network }}"
      services:
        esphome:
          # http://esphome.internal:6052
          container_name: esphome
          environment:
            - ESPHOME_DASHBOARD_USE_PING=true
          image: "{{ homeassistantfrigate_esphome_docker_image }}"
          logging: "{{ default_logging }}"
          ports:
            - "{{ homeassistantfrigate_esphome_port }}:6052"
          restart: unless-stopped
          volumes: "{{ esphome_volumes }}"
  notify:
    - restart homeassistant
    - update /etc/hosts
