---
- name: Start Home Assistant, Frigate and Mosquitto Docker containers
  vars:
    frigate_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_frigate_required_volumes.config }}:/config"
      - "{{ homeassistantfrigate_frigate_required_volumes.media }}:/media/frigate"

    frigate_tmpfs_volume:
      type: tmpfs # Optional ram-drive to reduce storage wear
      target: /tmp/cache
      tmpfs:
        size: "{{ homeassistantfrigate_frigate_tmpfs_size_mb * 1024 * 1024 }}"

    homeassistant_volumes:
      - "{{ homeassistantfrigate_required_volumes.config }}:/config"
      - "{{ homeassistantfrigate_required_volumes.dbus }}:/run/dbus:ro"
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_required_volumes.udev }}:/run/udev:ro"

    mosquitto_volumes:
      - "{{ homeassistantfrigate_required_volumes.localtime }}:/etc/localtime:ro"
      - "{{ homeassistantfrigate_required_volumes.timezone }}:/etc/timezone:ro"
      - "{{ homeassistantfrigate_mosquitto_required_volumes.config }}:/mosquitto/config:ro"
      - "{{ homeassistantfrigate_mosquitto_required_volumes.data }}:/mosquitto/data"
      - "{{ homeassistantfrigate_mosquitto_required_volumes.log }}:/mosquitto/log"

  community.docker.docker_compose_v2:
    project_name: homeassistant-frigate
    pull: always
    remove_orphans: true
    definition:
      services:
        frigate:
          container_name: frigate
          image: "{{ homeassistantfrigate_frigate_docker_image }}"
          devices: "{{ homeassistantfrigate_frigate_devices }}"
          environment: "{{ homeassistantfrigate_frigate_env }}"
          group_add:
            - "{{ getent_group.render[1] }}"
            - "{{ getent_group.video[1] }}"
          ports:
            - "{{ homeassistantfrigate_frigate_port }}:5000"
            - "{{ homeassistantfrigate_frigate_rtsp_port }}:1935"
            # RTSP restream https://docs.frigate.video/configuration/restream/
            - "8554:8554/tcp"
            - "8555:8555/tcp" # WebRTC over TCP
            - "8555:8555/udp" # WebRTC over UDP
          # *Disabled for security reasons*
          # Fix error: Unable to poll intel GPU stats: Failed to initialize PMU! (Operation not permitted)
          # https://github.com/blakeblackshear/frigate/issues/6028#issuecomment-1506283282
          #privileged: true
          restart: unless-stopped
          # https://docs.docker.com/reference/cli/docker/container/run/#security-opt
          # https://docs.docker.com/engine/security/seccomp/#run-without-the-default-seccomp-profile
          security_opt:
            - seccomp=unconfined
          shm_size: "{{ homeassistantfrigate_frigate_shm_size }}"
          volumes: "{{ frigate_volumes + ([frigate_tmpfs_volume] if homeassistantfrigate_frigate_tmpfs_size_mb > 0 else []) }}"

        homeassistant:
          container_name: homeassistant
          image: "{{ homeassistantfrigate_docker_image }}"
          devices: "{{ homeassistantfrigate_devices }}"
          # `network_mode: host` is required by the Google Cast integration:
          # https://www.home-assistant.io/integrations/cast/#home-assistant-container
          #network_mode: host
          ports:
            - "{{ homeassistantfrigate_port }}:8123"
          restart: unless-stopped
          # Apply this Apparmor policy (installed above) to allow the container to access bluetooth via dbus-broker
          # Run the following from the host to test: `sudo aa-status|grep docker-ble-policy`
          # https://docs.docker.com/reference/cli/docker/container/run/#security-opt
          security_opt:
            - "apparmor=docker-ble-policy"
          volumes: "{{ homeassistant_volumes + homeassistantfrigate_extra_volumes }}"

        mosquitto:
          container_name: mosquitto
          image: "{{ homeassistantfrigate_mosquitto_docker_image }}"
          # Use http://mosquitto:1883
          #ports:
          #  - "{{ homeassistantfrigate_mosquitto_port }}:1883"
          volumes: "{{ mosquitto_volumes }}"
