---
- name: Start Frigate Docker container
  vars:
    frigate_base_volumes:
      - "{{ homeassistantfrigate_frigate_required_volumes.config }}:/config"
      - "{{ homeassistantfrigate_frigate_required_volumes.media }}:/media/frigate"
    frigate_volumes: "{{ common_volumes + frigate_base_volumes }}"

    frigate_tmpfs_volume:
      type: tmpfs # Optional ram-drive to reduce storage wear
      target: /tmp/cache
      tmpfs:
        size: "{{ homeassistantfrigate_frigate_tmpfs_size_mb * 1024 * 1024 }}"
    frigate_env: "{{ homeassistantfrigate_frigate_env | default({}) | combine({'TZ': system_timezone.stdout.strip()}) }}"

  community.docker.docker_compose_v2:
    project_name: homeassistant-frigate-llm
    pull: always
    remove_orphans: true
    definition:
      networks: "{{ external_network }}"
      services:
        frigate:
          container_name: frigate
          image: "{{ homeassistantfrigate_frigate_docker_image }}"
          devices: "{{ homeassistantfrigate_frigate_devices }}"
          environment: "{{ frigate_env }}"
          group_add:
            - "{{ getent_group.render[1] }}"
            - "{{ getent_group.video[1] }}"
          logging: "{{ default_logging }}"
          mem_limit: "{{ homeassistantfrigate_frigate_memory }}"
          # Docs:
          # https://docs.docker.com/reference/compose-file/services/#memswap_limit
          # > If memswap_limit is set to the same value as memory, and memory
          # > is set to a positive integer, the container does not have
          # > access to swap.
          memswap_limit: "{{ homeassistantfrigate_frigate_memory_swap | default(homeassistantfrigate_frigate_memory) }}"
          ports:
            - "{{ homeassistantfrigate_frigate_port }}:5000"
            - "{{ homeassistantfrigate_frigate_rtsp_port }}:1935"
            # RTSP restream https://docs.frigate.video/configuration/restream/
            - "8554:8554/tcp"
            - "8555:8555/tcp" # WebRTC over TCP
            - "8555:8555/udp" # WebRTC over UDP
          restart: unless-stopped
          # https://docs.docker.com/reference/cli/docker/container/run/#security-opt
          # https://docs.docker.com/engine/security/seccomp/#run-without-the-default-seccomp-profile
          security_opt:
            - seccomp=unconfined
          shm_size: "{{ homeassistantfrigate_frigate_shm_size }}"
          volumes: "{{ frigate_volumes + ([frigate_tmpfs_volume] if homeassistantfrigate_frigate_tmpfs_size_mb > 0 else []) }}"

- name: Get Frigate container IP address
  community.docker.docker_container_info:
    name: frigate
  register: frigate_info

- name: Read Frigate configuration
  slurp:
    src: "{{ homeassistantfrigate_frigate_required_volumes.config }}/config.yml"
  register: frigate_config_raw

- name: Parse Frigate configuration YAML
  set_fact:
    frigate_config: "{{ frigate_config_raw.content | b64decode | from_yaml }}"

- name: Set go2rtc.webrtc.candidates to container IP:8555
  set_fact:
    frigate_config: "{{ frigate_config | combine({'go2rtc': {'webrtc': {'candidates': [ frigate_info.container.NetworkSettings.Networks['homeassistant-frigate_default'].IPAddress ~ ':8555' ]}}}, recursive=True) }}"

- name: Write updated Frigate configuration
  copy:
    dest: "{{ homeassistantfrigate_frigate_required_volumes.config }}/config.yml"
    content: "{{ frigate_config | to_nice_yaml(indent=2, sort_keys=False) }}"
    owner: root
    group: root
    mode: '0644'
  become: true
