---
# Must run before other docker*yml files
- import_tasks: docker_prerequisites.yml

- import_tasks: docker_homeassistant_frigate.yml

- import_tasks: docker_llm.yml
  when: homeassistantfrigate_install_llm

- import_tasks: docker_voice.yml
  when: homeassistantfrigate_install_voice
