---
# Home Assistant
- import_tasks: custom_components.yml
- import_tasks: themes.yml
- import_tasks: www.yml

- import_tasks: bluetooth.yml

# Mosquitto
- import_tasks: mosquitto.yml

# Start all Docker containers
- import_tasks: docker.yml

- import_tasks: docker_llm.yml
  when: homeassistantfrigate_install_llm
