---
- name: Validate mDNS configuration
  block:
    - name: Check for mDNS service conflicts
      assert:
        that:
          - not (homeassistantfrigate_install_avahi and homeassistantfrigate_install_matter)
        fail_msg: |
          ERROR: Cannot install both Avahi (homeassistantfrigate_install_avahi) and Matter/Thread (homeassistantfrigate_install_matter)
          as they both provide mDNS services and will conflict when using network_mode: host.
        success_msg: "mDNS configuration validated successfully"

    - name: mDNS advisory message
      debug:
        msg: |
          {% if homeassistantfrigate_install_matter %}
          Provisioning Matter/Thread, so Avahi will be disabled
          {% elif homeassistantfrigate_install_avahi %}
          Provisioning Avahi, so Matter/Thread will not be provisioned
          {% endif %}
      when: homeassistantfrigate_install_matter or homeassistantfrigate_install_avahi

    - import_tasks: avahi.yml
      when: homeassistantfrigate_install_avahi

    - name: Disable host Avahi daemon when not needed
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      become: true
      loop:
        - avahi-daemon.socket
        - avahi-daemon.service
      ignore_errors: true
      when: not homeassistantfrigate_install_avahi
  tags:
    - avahi
    - docker

- import_tasks: bluetooth.yml
- import_tasks: mosquitto.yml
- import_tasks: otbr.yml

- name: Install customizations
  block:
    - import_tasks: custom_components.yml
    - import_tasks: themes.yml
    - import_tasks: www.yml
  tags: customizations

- name: Configure Docker containers
  block:
    - import_tasks: docker_prerequisites.yml

    # Must come first, because it creates the shared bridge network
    - import_tasks: docker_homeassistant.yml
      tags:
        - govee2mqtt
        - homeassistant
        - mosquitto

    - import_tasks: docker_esphome.yml
      tags: esphome
      when: homeassistantfrigate_install_esphome

    - import_tasks: docker_frigate.yml
      tags: frigate
      when: homeassistantfrigate_install_frigate

    - import_tasks: docker_llm.yml
      tags: llm
      when: homeassistantfrigate_install_llm

    - import_tasks: docker_matter.yml
      tags: matter
      when: homeassistantfrigate_install_matter

    - import_tasks: docker_voice.yml
      tags: voice
      when: homeassistantfrigate_install_voice
  tags: docker
