---
# Home Assistant
- import_tasks: avahi.yml
- import_tasks: bluetooth.yml
- import_tasks: custom_components.yml
- import_tasks: themes.yml
- import_tasks: www.yml

# Mosquitto
- import_tasks: mosquitto.yml

# Docker containers
- name: Configure Docker containers
  block:
    - import_tasks: docker_prerequisites.yml
    - import_tasks: docker_homeassistant.yml
    - import_tasks: docker_frigate.yml
      when: homeassistantfrigate_install_frigate
    - import_tasks: docker_llm.yml
      when: homeassistantfrigate_install_llm
    - import_tasks: docker_voice.yml
      when: homeassistantfrigate_install_voice
    - import_tasks: docker_esphome.yml
      when: homeassistantfrigate_install_esphome
  tags: docker
