---
- name: Create themes/ directory
  file:
    path: "{{ homeassistantfrigate_required_volumes.config }}/themes/"
    state: directory
    owner: root
    group: root
  become: true

- name: Install IBM1970 theme
  get_url:
    url: https://raw.githubusercontent.com/andornaut/homeassistant-ibm1970-theme/main/themes/ibm1970.yaml
    dest: "{{ homeassistantfrigate_required_volumes.config }}/themes/"
  become: true
