---
galaxy_info:
  author: andornaut
  description: Provision Docker CE and Docker Compose on Ubuntu
  license: MIT
  min_ansible_version: "2.19"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - docker
    - containers
    - ubuntu
